-- Step 3 seed: 16 developers, rules checked against their official pages on 2026-09-23.
-- Re-check source_url before trusting a line; update last_verified when you do.

insert into public.developers
  (name, slug, website, transferable, fee, who_pays, process, typical_delay, restrictions, source_url, last_verified)
values
('FabFilter', 'fabfilter', 'https://www.fabfilter.com', true,
 'About €10 (a "License Transfer" bought in the FabFilter account)', 'Seller',
 'The seller buys a License Transfer in their FabFilter account, then transfers the license to the buyer''s full name and email from that account.',
 'Immediate once the seller does it',
 'Educational and NFR licenses can''t be transferred. Bundles can only be transferred as a whole.',
 'https://www.fabfilter.com/support/faq', '2026-09-23'),

('Soundtoys', 'soundtoys', 'https://www.soundtoys.com', true,
 '$25 iLok transfer fee (charged by PACE)', 'Seller (paid in iLok License Manager)',
 'The seller transfers the license to the buyer''s iLok account in iLok License Manager, then emails Soundtoys support with the buyer''s email and iLok ID so the registration is updated.',
 null,
 'Transfers need Soundtoys'' written consent and can be refused.',
 'https://support.soundtoys.com/article/99-license-transfers', '2026-09-23'),

('iZotope', 'izotope', 'https://www.izotope.com', true,
 'Free (plus the $25 iLok fee if the product was activated with iLok)', null,
 'The original owner contacts iZotope Account Support to request the transfer.',
 null,
 'Only full, purchased licenses. Time-limited, educational, NFR and retail/hardware-bundled licenses aren''t eligible. A product can only be transferred once.',
 'https://support.izotope.com/hc/en-us/articles/6658051682449-iZotope-s-License-Transfer-Policy', '2026-09-23'),

('Waves', 'waves', 'https://www.waves.com', true,
 '5% of the product''s list price (min $10, max $150 per transfer)', 'Seller (registered owner)',
 'The seller deactivates the licenses, fills in the transfer form on waves.com and pays through the secure link Waves sends.',
 'Up to 3 business days',
 'Licenses must be registered for 3+ months, version 9 or later, and covered by an active Waves Update Plan. Creative Access subscriptions can''t be transferred.',
 'https://www.waves.com/support/transfer-of-ownership', '2026-09-23'),

('Native Instruments', 'native-instruments', 'https://www.native-instruments.com', true,
 null, null,
 'The seller creates a Transfer ID in their NI account (Products and licenses → Transfer a license). The buyer imports it on NI''s Import License page.',
 'Immediate (self-service)',
 null,
 'https://support.native-instruments.com/support/solutions/articles/69000879192-how-to-request-a-license-transfer-id-for-your-ni-product', '2026-09-23'),

('Arturia', 'arturia', 'https://www.arturia.com', true,
 'Free for first-hand licenses, €10 if the license was itself bought second-hand', null,
 'The seller opens a support request (Reinstalling & Reselling → transfer my license to another user) with the buyer''s Arturia account email.',
 null,
 'The product must have been registered for at least 6 months.',
 'https://support.arturia.com/hc/en-us/articles/4405741338642-How-to-resell-my-product-license', '2026-09-23'),

('Universal Audio', 'universal-audio', 'https://www.uaudio.com', false,
 null, null,
 'UAD DSP plug-ins only move together with the Apollo, Satellite or UAD-2 hardware they are registered to (all plug-ins or none).',
 null,
 'Plug-in licenses can''t be sold on their own, only with the hardware.',
 'https://help.uaudio.com/hc/en-us/articles/206238366-How-To-Transfer-Ownership-of-Apollo-Satellite-or-PCIe-UAD-2-Devices', '2026-09-23'),

('Plugin Alliance', 'plugin-alliance', 'https://www.plugin-alliance.com', false,
 null, null,
 'Self-service transfers are currently unavailable. Requests may be handled case by case by Native Instruments support (Plugin Alliance''s owner).',
 null,
 'Previous policy: $20 per plug-in (max $50), paid by the buyer; subscription licenses and already-transferred licenses excluded.',
 'https://support.plugin-alliance.com/hc/en-us/articles/9754979495837-License-Transfer', '2026-09-23'),

('Valhalla DSP', 'valhalla-dsp', 'https://valhalladsp.com', true,
 null, null,
 'Automatic transfers are temporarily disabled: the seller asks for the transfer through Valhalla''s support form. The buyer needs a Valhalla DSP account.',
 null,
 'Only licenses bought on valhalladsp.com.',
 'https://valhalladsp.com/faq/purchasing/', '2026-09-23'),

('Xfer Records', 'xfer-records', 'https://xferrecords.com', false,
 null, null, null, null,
 'Xfer Records doesn''t allow license transfers (fraud concerns, stated by Steve Duda since 2019).',
 'https://xferrecords.com/forums/general/can-you-sell-or-transfer-your-serum-license', '2026-09-23'),

('u-he', 'u-he', 'https://u-he.com', true,
 'Free after 9 months; €15 transfer token before that', null,
 'Request it with u-he''s contact form ("Transfer your license") or at support@u-he.com. The buyer receives the new license directly from u-he.',
 'Processed manually by u-he support',
 'Not possible during the first 6 weeks after purchase.',
 'https://u-he.com/support/faq/contact/license-transfer/', '2026-09-23'),

('Spectrasonics', 'spectrasonics', 'https://www.spectrasonics.net', true,
 '$50 per instrument', 'Usually the seller (buyer and seller can agree otherwise)',
 'The original purchaser emails info@spectrasonics.net. Each request is reviewed case by case.',
 'A few weeks',
 'Only the original purchaser can transfer, once per license. Omnisphere Sonic Extensions only with the parent Omnisphere license.',
 'https://www.spectrasonics.net/support/knowledgebase/article/view/151/23', '2026-09-23'),

('Eventide', 'eventide', 'https://www.eventideaudio.com', true,
 '$25 iLok transfer fee (charged by PACE); no Eventide fee', 'Seller (paid in iLok License Manager)',
 'The seller transfers the license to the buyer''s iLok account in iLok License Manager.',
 'Immediate',
 null,
 'https://www.eventideaudio.com/forums/topic/license-transfer/', '2026-09-23'),

('Softube', 'softube', 'https://www.softube.com', true,
 '$25 iLok fee per license or bundle (max $50 per order)', null,
 'The license is transferred through iLok License Manager (see Softube''s guide).',
 null,
 'Not before 90 days after the license was deposited.',
 'https://www.softube.com/support/licenses/how-can-i-transfer-my-license-to-another-user-account', '2026-09-23'),

('Toontrack', 'toontrack', 'https://www.toontrack.com', true,
 '$15 administration fee per serial number', null,
 'Contact Toontrack support, choose "License Transfer" and pay the fee for each serial number.',
 null,
 'The serial must have been registered to the account for 30+ days.',
 'https://www.toontrack.com/faq/transfer-of-license-and-multiple-installs-important-information/', '2026-09-23'),

('Spitfire Audio', 'spitfire-audio', 'https://www.spitfireaudio.com', false,
 null, null, null, null,
 'Spitfire''s license forbids reselling or transferring its products.',
 'https://spitfireaudio.zendesk.com/hc/en-us/articles/204913456-I-don-t-use-my-product-anymore-can-I-sell-it-on', '2026-09-23');

-- Plugins: slug derived from the name.
insert into public.plugins (developer_id, name, slug, category)
select d.id, p.name,
       trim(both '-' from lower(regexp_replace(p.name, '[^a-zA-Z0-9]+', '-', 'g'))),
       p.category
from (values
  ('fabfilter', 'Pro-Q 4', 'eq'),
  ('fabfilter', 'Pro-Q 3', 'eq'),
  ('fabfilter', 'Pro-C 2', 'compression'),
  ('fabfilter', 'Pro-MB', 'compression'),
  ('fabfilter', 'Pro-L 2', 'mastering'),
  ('fabfilter', 'Pro-R 2', 'reverb-delay'),
  ('fabfilter', 'Timeless 3', 'reverb-delay'),
  ('fabfilter', 'Saturn 2', 'saturation'),
  ('fabfilter', 'Total Bundle', 'bundles'),
  ('soundtoys', 'Decapitator', 'saturation'),
  ('soundtoys', 'Radiator', 'saturation'),
  ('soundtoys', 'EchoBoy', 'reverb-delay'),
  ('soundtoys', 'Little AlterBoy', 'utilities'),
  ('soundtoys', 'Soundtoys 5', 'bundles'),
  ('izotope', 'Ozone 11 Advanced', 'mastering'),
  ('izotope', 'Ozone 11 Standard', 'mastering'),
  ('izotope', 'Neutron 4', 'utilities'),
  ('izotope', 'RX 11 Standard', 'utilities'),
  ('izotope', 'Nectar 4', 'utilities'),
  ('waves', 'SSL E-Channel', 'eq'),
  ('waves', 'CLA-76', 'compression'),
  ('waves', 'H-Delay', 'reverb-delay'),
  ('waves', 'Abbey Road Chambers', 'reverb-delay'),
  ('waves', 'Mercury', 'bundles'),
  ('native-instruments', 'Komplete 14 Standard', 'bundles'),
  ('native-instruments', 'Kontakt 8', 'sample-libraries'),
  ('native-instruments', 'Massive X', 'synths'),
  ('native-instruments', 'Guitar Rig 7 Pro', 'utilities'),
  ('arturia', 'Pigments', 'synths'),
  ('arturia', 'Analog Lab Pro', 'synths'),
  ('arturia', 'V Collection X', 'bundles'),
  ('arturia', 'FX Collection 5', 'bundles'),
  ('universal-audio', 'Teletronix LA-2A Collection', 'compression'),
  ('universal-audio', 'Pultec Passive EQ Collection', 'eq'),
  ('plugin-alliance', 'bx_console SSL 4000 E', 'eq'),
  ('plugin-alliance', 'bx_digital V3', 'mastering'),
  ('plugin-alliance', 'Shadow Hills Mastering Compressor', 'compression'),
  ('valhalla-dsp', 'VintageVerb', 'reverb-delay'),
  ('valhalla-dsp', 'Room', 'reverb-delay'),
  ('valhalla-dsp', 'Delay', 'reverb-delay'),
  ('valhalla-dsp', 'Shimmer', 'reverb-delay'),
  ('xfer-records', 'Serum 2', 'synths'),
  ('xfer-records', 'LFOTool', 'utilities'),
  ('u-he', 'Diva', 'synths'),
  ('u-he', 'Repro', 'synths'),
  ('u-he', 'Hive 2', 'synths'),
  ('u-he', 'Zebra2', 'synths'),
  ('u-he', 'Satin', 'saturation'),
  ('spectrasonics', 'Omnisphere', 'synths'),
  ('spectrasonics', 'Keyscape', 'sample-libraries'),
  ('spectrasonics', 'Trilian', 'sample-libraries'),
  ('spectrasonics', 'Stylus RMX', 'sample-libraries'),
  ('eventide', 'Blackhole', 'reverb-delay'),
  ('eventide', 'H3000 Factory', 'reverb-delay'),
  ('eventide', 'SP2016 Reverb', 'reverb-delay'),
  ('eventide', 'UltraTap', 'reverb-delay'),
  ('softube', 'Tube-Tech CL 1B', 'compression'),
  ('softube', 'Tape', 'saturation'),
  ('softube', 'Model 72 Synthesizer System', 'synths'),
  ('toontrack', 'Superior Drummer 3', 'sample-libraries'),
  ('toontrack', 'EZdrummer 3', 'sample-libraries'),
  ('toontrack', 'EZkeys 2', 'sample-libraries'),
  ('spitfire-audio', 'BBC Symphony Orchestra Professional', 'sample-libraries'),
  ('spitfire-audio', 'Albion ONE', 'sample-libraries')
) as p(dev_slug, name, category)
join public.developers d on d.slug = p.dev_slug;
