-- Step 13: 50 more developers and their flagship products (incl. many VSTi/synth makers).
-- Transfer rules checked against each developer's official pages on 2026-09-25.

insert into public.developers
  (name, slug, website, transferable, fee, who_pays, process, typical_delay, restrictions, source_url, last_verified, no_fee)
values
('Vengeance Sound', 'vengeance-sound', 'https://www.vengeance-sound.com', false,
 null, null, null, null,
 'Vengeance Sound''s terms of use say reselling of any Vengeance Sound product is prohibited and will be legally pursued.',
 'https://www.vengeance-sound.com/terms.php', '2026-09-25', false),
('Synapse Audio', 'synapse-audio', 'https://www.synapse-audio.com', true,
 'Free for the first transfer; €20 for any later resale', 'Seller',
 'The seller emails Synapse Audio with the buyer''s full name and email; the buyer needs a Synapse Audio account.',
 'Usually under a week',
 null, 'https://www.synapse-audio.com/eula.html', '2026-09-25', true),
('Tone2', 'tone2', 'https://www.tone2.com', true,
 '€19.99 per product', 'Seller',
 'The seller confirms the software is fully uninstalled and the keyfile deleted, then requests the transfer; the license becomes NFR afterwards.',
 null,
 'One transfer per license only. Bundles, NFR, coupon-discounted licenses and copies bought through a reseller can''t be transferred.',
 'https://www.tone2.com/license.html', '2026-09-25', false),
('Sonic Charge', 'sonic-charge', 'https://soniccharge.com', true,
 '$10 + VAT', null,
 'The seller contacts Sonic Charge support to move the license, linked to the buyer''s email.',
 null,
 'Not possible within 120 days of purchase. Unregistered (promo/free) licenses can''t be sold.',
 'https://soniccharge.com/EULA', '2026-09-25', false),
('Vital Audio', 'vital-audio', 'https://vital.audio', null,
 null, null, null, null,
 'Vital Audio doesn''t publish a clear resale/transfer policy for the paid "Vital Pro" tier. Ask their support before buying or selling.',
 null, null, false),
('Audio Damage', 'audio-damage', 'https://www.audiodamage.com', false,
 null, null, null, null,
 'Audio Damage''s official support page states they do not offer license transfers.',
 'https://www.audiodamage.com/pages/support', '2026-09-25', false),
('Reason Studios', 'reason-studios', 'https://www.reasonstudios.com', false,
 null, null, null, null,
 'Individual Rack Extension licenses (instruments and effects inside the Reason rack) are tied to the original account and can''t be sold or transferred; there is no official process to move one to a new owner.',
 'https://help.reasonstudios.com/hc/en-us/articles/360002216273-Buying-selling-used-Reason-Studios-products', '2026-09-25', false),
('Roland Cloud', 'roland-cloud', 'https://www.rolandcloud.com', false,
 null, null, null, null,
 'Roland''s own support articles state Lifetime Key use rights are not transferable, descendible or inheritable, and accounts can''t be sold. EU consumer law may override this for EU buyers/sellers; check with Roland first.',
 'https://support.roland.com/hc/en-us/articles/4412162297243-Roland-Cloud-What-is-a-Lifetime-Key-and-how-does-it-work', '2026-09-25', false),
('Initial Audio', 'initial-audio', 'https://initialaudio.com', false,
 null, null, null, null,
 'Initial Audio''s policy states every license is single-user and non-transferable; copying, reselling or trading is prohibited.',
 'https://initialaudio.com/policy/', '2026-09-25', false),
('W.A. Production', 'wa-production', 'https://www.waproduction.com', false,
 null, null, null, null,
 'W.A. Production''s help center states they do not support license transfers.',
 'https://waproduction.zendesk.com/hc/en-us/articles/360015783680-Can-I-transfer-my-license-to-someone-else', '2026-09-25', false),
('Klevgrand', 'klevgrand', 'https://klevgrand.com', false,
 null, null, null, null,
 'Klevgrand accounts and licenses are personal and can''t be transferred to a third party, except in rare cases decided by Klevgrand itself.',
 'https://klevgrand.com/terms', '2026-09-25', false),
('Xhun Audio', 'xhun-audio', 'https://www.xhun-audio.com', null,
 null, null, null, null,
 'Xhun Audio describes its software as leased rather than sold and says a resold license can be blocked at any time; no formal transfer program is published.',
 null, null, false),
('Sinevibes', 'sinevibes', 'https://www.sinevibes.com', true,
 null, null,
 'The seller emails Sinevibes with the plugins to transfer and the buyer''s email address.',
 null, null,
 'https://www.sinevibes.com/questions-answers/', '2026-09-25', false),
('Wave Alchemy', 'wave-alchemy', 'https://www.wavealchemy.co.uk', true,
 null, null,
 'The seller emails Wave Alchemy support to transfer a native (VST/AU/AAX) plugin license to the buyer.',
 null,
 'One-time transfer only; the license can''t be resold again afterwards. Sample packs (as opposed to plugins) are never transferable.',
 'https://www.wavealchemy.co.uk/support/faq/', '2026-09-25', false),
('PSP Audioware', 'psp-audioware', 'https://www.pspaudioware.com', true,
 'Free (no PACE license-transfer fee charged)', null,
 'The seller contacts PSP support with both the seller''s and buyer''s user IDs and the product name; PSP approves the move.',
 null,
 'The EULA formally describes licenses as non-transferable, but PSP approves transfers on request in practice.',
 'https://www.pspaudioware.com/support', '2026-09-25', true),
('Kush Audio', 'kush-audio', 'https://thehouseofkush.com', null,
 null, null, null, null,
 'Kush Audio doesn''t publish a clear resale/transfer policy for its iLok-based plugins. Ask their support before buying or selling.',
 null, null, false),
('Black Rooster Audio', 'black-rooster-audio', 'https://blackroosteraudio.com', true,
 null, null,
 'The seller emails helpdesk@blackroosteraudio.com with the Black Rooster account email of the buyer.',
 'Usually under 2 business days',
 'Unregistered (free/promo) licenses can''t be sold.',
 'https://blackroosteraudio.com/en/faq', '2026-09-25', false),
('Nomad Factory', 'nomad-factory', 'https://www.nomadfactory.com', true,
 null, null,
 'The seller contacts Nomad Factory with the product''s serial number and the buyer''s full name and email.',
 'Up to 24 hours',
 'Licenses originally activated via iLok/PACE can''t be transferred, since Nomad Factory no longer supports that system.',
 'https://help.nomadfactory.com/faqs/f70-What-is-your-license-transfer-policy/', '2026-09-25', false),
('Wave Arts', 'wave-arts', 'https://wavearts.com', true,
 'Free', null,
 'The seller contacts Wave Arts support to move the license to the buyer.',
 null, null,
 'https://wavearts.com/support/faq', '2026-09-25', true),
('Flux', 'flux-audio', 'https://www.flux.audio', true,
 'iLok transfer fee only (charged by PACE); no Flux fee', 'Seller',
 'The seller transfers the license to the buyer''s iLok account in iLok License Manager; Flux is not involved and no permission from Flux is needed.',
 null, null,
 'https://www.flux.audio/knowledge-base/license-transfers/', '2026-09-25', false),
('Sonimus', 'sonimus', 'https://sonimus.com', true,
 '20% of the product''s retail price', 'Buyer',
 'The buyer pays the transfer fee via PayPal to Sonimus, who then moves the license.',
 null,
 'One transfer per license; the license becomes NFR afterwards and can''t be resold again.',
 'https://sonimus.com/sonimus-client-software-license-agreement', '2026-09-25', false),
('Cytomic', 'cytomic', 'https://cytomic.com', true,
 '$29', null,
 'The seller contacts Cytomic support before selling to confirm the transfer, then pays the fee.',
 null,
 'Second-hand (already-transferred) licenses can''t be resold again. Contact support first to confirm the transfer is possible.',
 'https://cytomic.com/faq/', '2026-09-25', false),
('TBProAudio', 'tbproaudio', 'https://www.tbproaudio.de', true,
 null, null,
 'The seller submits a transfer request per TBProAudio''s License Transfer Policy page, cc''ing the buyer.',
 null,
 'A license can only be transferred after being owned for 90 days.',
 'https://www.tbproaudio.de/support/license-transfer-policy', '2026-09-25', false),
('DDMF', 'ddmf', 'https://ddmf.eu', true,
 '$5 per plugin', null,
 'The seller contacts DDMF to transfer the license key to the buyer.',
 null,
 'A plugin bought as part of a discounted bundle can only be transferred together with the whole bundle, not individually.',
 'https://ddmf.eu/faq/', '2026-09-25', false),
('HOFA', 'hofa', 'https://hofa-plugins.de', null,
 null, null, null, null,
 'HOFA-Plugins'' support pages cover moving a license between your own computers but don''t publish a policy for transferring to a different person.',
 null, null, false),
('Denise Audio', 'denise-audio', 'https://www.deniseaudio.com', false,
 null, null, null, null,
 'Denise Audio''s EULA grants a personal, non-transferable license and the company states it does not currently offer license transfers.',
 'https://www.deniseaudio.com/eula', '2026-09-25', false),
('Two Notes', 'two-notes', 'https://www.two-notes.com', false,
 null, null, null, null,
 'Two Notes'' terms state that DynIR cabinet licenses can''t be resold, sublicensed or transferred to a third party by the customer.',
 'https://www.two-notes.com/en/terms-and-conditions/', '2026-09-25', false),
('Nembrini Audio', 'nembrini-audio', 'https://www.nembriniaudio.com', true,
 '$20 per license', 'Buyer',
 'The seller requests the transfer; Nembrini Audio approves it and moves the license to the buyer''s account.',
 null, null,
 'https://www.nembriniaudio.com/policies/terms-of-service', '2026-09-25', false),
('Mercuriall Audio', 'mercuriall-audio', 'https://mercuriall.com', null,
 null, null, null, null,
 'Mercuriall Audio has long been reported as not offering license transfers, but no official transfer policy page is published.',
 null, null, false),
('Audio Assault', 'audio-assault', 'https://audioassault.mx', null,
 null, null, null, null,
 'Audio Assault''s public FAQ doesn''t cover license transfers; buyers report the company has handled transfers informally on request.',
 null, null, false),
('Krotos', 'krotos', 'https://www.krotosaudio.com', false,
 null, null, null, null,
 'Krotos'' terms state a license can''t be transferred, assigned or disposed of without Krotos'' prior written consent, and resale of its sound libraries is expressly prohibited.',
 'https://www.krotosaudio.com/terms-conditions/', '2026-09-25', false),
('Auburn Sounds', 'auburn-sounds', 'https://www.auburnsounds.com', false,
 null, null, null, null,
 'Auburn Sounds'' own FAQ states they do not support license transfers; its terms describe the license as non-transferable.',
 'https://www.auburnsounds.com/faq/Does-Auburn-Sounds-support-licence-transferts.html', '2026-09-25', false),
('Sample Logic', 'sample-logic', 'https://www.samplelogic.com', false,
 null, null, null, null,
 'Sample Logic''s license agreement forbids assigning, transferring, reselling or sharing its products; only moving a license between your own machines is supported.',
 'https://www.samplelogic.com/terms-license-agreement/', '2026-09-25', false),
('Aaron Venture', 'aaron-venture', 'https://www.aaronventure.com', false,
 null, null, null, null,
 'Aaron Venture''s EULA grants a personal, non-transferable license and forbids resale or redistribution.',
 'https://www.aaronventure.com/eula', '2026-09-25', false),
('Precision Sound', 'precision-sound', 'https://store.precisionsound.net', false,
 null, null, null, null,
 'Precision Sound''s terms forbid distributing, selling, reselling, lending or otherwise transferring its content; only the original purchaser may use it.',
 'https://store.precisionsound.net/terms-conditions/', '2026-09-25', false),
('In Session Audio', 'in-session-audio', 'https://insessionaudio.com', false,
 null, null, null, null,
 'In Session Audio''s EULA doesn''t allow license transfers; libraries are watermarked to each customer.',
 'https://insessionaudio.com/faq/', '2026-09-25', false),
('Auddict', 'auddict', 'https://auddict.com', null,
 null, null, null, null,
 'Auddict''s EULA prohibits resale, but the company has approved individual transfer requests case by case, at its sole discretion, with inconsistent results reported by buyers.',
 'https://auddict.com/terms', '2026-09-25', false),
('Chris Hein Instruments', 'chris-hein-instruments', 'https://www.chrishein.net', true,
 '€25', 'Seller',
 'The transfer is handled through Best Service (Chris Hein''s main retailer): the seller pays the fee and provides the buyer''s details.',
 null, null,
 'https://www.bestservice.com/en/reselling_our_products.html', '2026-09-25', false),
('Zero-G', 'zero-g', 'https://zero-g.co.uk', false,
 null, null, null, null,
 'Zero-G''s license is granted to the original end-user only and is explicitly not transferable; resale or redistribution is forbidden.',
 'https://zero-g.co.uk/pages/terms-and-conditions', '2026-09-25', false),
('Soniccouture', 'soniccouture', 'https://www.soniccouture.com', true,
 '€25 / $25', null,
 'The seller submits a support ticket; Soniccouture reviews and manually processes the transfer.',
 null,
 'Covers Kontakt Player-based products; the standard license wording otherwise forbids resale, so this is an exception Soniccouture grants on request.',
 'https://www.soniccouture.com/en/terms-and-conditions/', '2026-09-25', false),
('Exponential Audio', 'exponential-audio', 'https://www.exponentialaudio.com', true,
 'Free (plus the iLok transfer fee if the product was activated with iLok)', null,
 'Now part of iZotope: the seller asks iZotope support to move the license, the same way as any other iZotope product.',
 null, null,
 'https://support.izotope.com/hc/en-us/articles/6658051682449-iZotope-s-License-Transfer-Policy', '2026-09-25', false),
('AudioThing', 'audiothing', 'https://www.audiothing.net', true,
 '$5/€5 per product (single transfer); $25/€25 for a full account or 5+ plugins at once', 'Seller',
 'The seller requests the transfer from their registered email and pays the fee; AudioThing re-registers the license to the buyer.',
 null,
 'NFR (not-for-resale) licenses can''t be transferred.',
 'https://www.audiothing.net/eula/transfer-fees/', '2026-09-25', false),
('Wavesfactory', 'wavesfactory', 'https://www.wavesfactory.com', true,
 '25% of the plugin''s regular price', 'Seller',
 'The seller opens a support ticket and pays the fee via PayPal; Wavesfactory then moves the license.',
 null,
 'If other purchases are on the same invoice, they are removed from the seller''s account as part of the transfer.',
 'https://www.wavesfactory.com/support/', '2026-09-25', false),
('Metric Halo', 'metric-halo', 'https://mhsecure.com', null,
 null, null, null, null,
 'Metric Halo''s older EULA allows transferring a license with notice to Metric Halo, except Native-only licenses which can''t be transferred; current iLok-based licensing may differ. Confirm with Metric Halo before buying or selling.',
 'http://www.mhlabs.com/metric_halo/support/MH_EULA.pdf', '2026-09-25', false),
('Cinematique Instruments', 'cinematique-instruments', 'https://cinematique-instruments.com', null,
 null, null, null, null,
 'Cinematique Instruments doesn''t publish a clear resale/transfer policy. Ask their support before buying or selling.',
 null, null, false),
('Rast Sound', 'rast-sound', 'https://rastsound.com', null,
 null, null, null, null,
 'Rast Sound''s user license agreement doesn''t clearly address resale or transfer to a new owner. Ask their support before buying or selling.',
 null, null, false),
('Wusik', 'wusik', 'https://www.wusik.com', null,
 null, null, null, null,
 'Wusik has reportedly allowed free license transfers via its support area, but no official transfer policy page is published.',
 null, null, false),
('Fracture Sounds', 'fracture-sounds', 'https://fracturesounds.com', false,
 null, null, null, null,
 'Fracture Sounds'' terms state licenses, free or paid, are personal and non-transferable, except in rare cases at their sole discretion.',
 'https://fracturesounds.com/terms-conditions/', '2026-09-25', false),
('Big Fish Audio', 'big-fish-audio', 'https://www.bigfishaudio.com', false,
 null, null, null, null,
 'Big Fish Audio''s license agreement is non-exclusive and non-transferable and expressly forbids resale, rental or transfer of its products.',
 'https://help.bigfishaudio.com/help/end-user-license-agreement-2', '2026-09-25', false),
('Vir2 Instruments', 'vir2-instruments', 'https://www.vir2.com', false,
 null, null, null, null,
 'Vir2''s license is granted to the individual end user only and expressly forbids resale, rental, loan, gift or transfer.',
 'https://www.vir2.com/support/faq/', '2026-09-25', false);

insert into public.plugins (developer_id, name, slug, category)
select d.id, p.name, p.slug, p.category
from (values
  ('vengeance-sound', 'VPS Avenger', 'vps-avenger', 'synths'),
  ('vengeance-sound', 'VPS Multiband Distortion 2', 'vps-multiband-distortion-2', 'saturation'),

  ('synapse-audio', 'Dune 3', 'dune-3', 'synths'),
  ('synapse-audio', 'The Legend', 'the-legend', 'synths'),
  ('synapse-audio', 'Antidote 2', 'antidote-2', 'utilities'),

  ('tone2', 'Icarus 2', 'icarus-2', 'synths'),
  ('tone2', 'Nemesis', 'nemesis', 'synths'),
  ('tone2', 'Saurus', 'saurus', 'synths'),
  ('tone2', 'FireBird 2', 'firebird-2', 'synths'),

  ('sonic-charge', 'Synplant 2', 'synplant-2', 'synths'),
  ('sonic-charge', 'Microtonic', 'microtonic', 'synths'),
  ('sonic-charge', 'Bitspeek', 'bitspeek', 'utilities'),

  ('vital-audio', 'Vital', 'vital', 'synths'),

  ('audio-damage', 'Fluid', 'fluid', 'synths'),
  ('audio-damage', 'Kombinat XL', 'kombinat-xl', 'synths'),
  ('audio-damage', 'Discord 4', 'discord-4', 'utilities'),

  ('reason-studios', 'Europa', 'europa', 'synths'),
  ('reason-studios', 'Grain', 'grain', 'synths'),
  ('reason-studios', 'Subtractor', 'subtractor', 'synths'),

  ('roland-cloud', 'JUPITER-8', 'jupiter-8', 'synths'),
  ('roland-cloud', 'JUNO-106', 'juno-106', 'synths'),
  ('roland-cloud', 'TR-808', 'tr-808', 'synths'),
  ('roland-cloud', 'SYSTEM-8', 'system-8', 'synths'),

  ('initial-audio', 'Poly Verse', 'poly-verse', 'synths'),
  ('initial-audio', 'Heat Up 2', 'heat-up-2', 'saturation'),
  ('initial-audio', 'Dirty Tape', 'dirty-tape', 'saturation'),

  ('wa-production', 'InstaChord', 'instachord', 'utilities'),
  ('wa-production', 'ImageWide', 'imagewide', 'utilities'),
  ('wa-production', 'ABL3', 'abl3', 'compression'),

  ('klevgrand', 'DAW Cassette', 'daw-cassette', 'saturation'),
  ('klevgrand', 'Brusfri', 'brusfri', 'utilities'),
  ('klevgrand', 'Chubby Tubes', 'chubby-tubes', 'saturation'),

  ('xhun-audio', 'LittleOne', 'littleone', 'synths'),
  ('xhun-audio', 'DarkStar', 'darkstar', 'synths'),
  ('xhun-audio', 'PolyKB II', 'polykb-ii', 'synths'),

  ('sinevibes', 'Turbine', 'turbine', 'synths'),
  ('sinevibes', 'Robotomata', 'robotomata', 'utilities'),

  ('wave-alchemy', 'Space', 'space', 'reverb-delay'),
  ('wave-alchemy', 'Transform', 'transform', 'synths'),
  ('wave-alchemy', 'PhatMatik', 'phatmatik', 'sample-libraries'),

  ('psp-audioware', 'PSP Vintage Warmer 2', 'psp-vintage-warmer-2', 'saturation'),
  ('psp-audioware', 'PSP Xenon', 'psp-xenon', 'compression'),
  ('psp-audioware', 'PSP MixPack', 'psp-mixpack', 'bundles'),

  ('kush-audio', 'Clariphonic DSP', 'clariphonic-dsp', 'eq'),
  ('kush-audio', 'UBK Fatso Jr', 'ubk-fatso-jr', 'saturation'),
  ('kush-audio', 'Electra', 'electra', 'compression'),

  ('black-rooster-audio', 'VLA-2A', 'vla-2a', 'compression'),
  ('black-rooster-audio', 'VLA-3A', 'vla-3a', 'compression'),
  ('black-rooster-audio', 'Ariva-N', 'ariva-n', 'channel-strips'),

  ('nomad-factory', 'Blue Tubes Bundle', 'blue-tubes-bundle', 'bundles'),
  ('nomad-factory', 'Magnetic II', 'magnetic-ii', 'saturation'),
  ('nomad-factory', 'Bus Driver', 'bus-driver', 'mastering'),

  ('wave-arts', 'MultiDynamics', 'multidynamics', 'compression'),
  ('wave-arts', 'TrackPlug', 'trackplug', 'channel-strips'),
  ('wave-arts', 'Panorama', 'panorama', 'utilities'),

  ('flux-audio', 'IRCAM Verb V3', 'ircam-verb-v3', 'reverb-delay'),
  ('flux-audio', 'Elixir', 'elixir', 'eq'),
  ('flux-audio', 'Solera', 'solera', 'mastering'),

  ('sonimus', 'Satson', 'satson', 'channel-strips'),
  ('sonimus', 'British Channel', 'british-channel', 'channel-strips'),
  ('sonimus', 'SonEQ', 'soneq', 'eq'),

  ('cytomic', 'The Glue', 'the-glue', 'compression'),
  ('cytomic', 'The Drop', 'the-drop', 'compression'),

  ('tbproaudio', 'dpMeter5', 'dpmeter5', 'utilities'),
  ('tbproaudio', 'ISOL8', 'isol8', 'eq'),
  ('tbproaudio', 'mvMeter2', 'mvmeter2', 'utilities'),

  ('ddmf', 'MetaPlugin', 'metaplugin', 'utilities'),
  ('ddmf', 'IIEQ Pro', 'iieq-pro', 'eq'),
  ('ddmf', 'NYQ', 'nyq', 'utilities'),

  ('denise-audio', 'Bandsaw', 'bandsaw', 'saturation'),
  ('denise-audio', 'Sidechain', 'sidechain', 'compression'),
  ('denise-audio', 'Bloom', 'bloom', 'reverb-delay'),

  ('two-notes', 'Torpedo Remote', 'torpedo-remote', 'guitar-amps'),
  ('two-notes', 'Wall of Sound', 'wall-of-sound', 'guitar-amps'),
  ('two-notes', 'Gojira Suite', 'gojira-suite', 'guitar-amps'),

  ('nembrini-audio', 'British Lead', 'british-lead', 'guitar-amps'),
  ('nembrini-audio', 'Fireclaw', 'fireclaw', 'guitar-amps'),
  ('nembrini-audio', 'Mercury Tube Preamp', 'mercury-tube-preamp', 'channel-strips'),

  ('mercuriall-audio', 'U530', 'u530', 'guitar-amps'),
  ('mercuriall-audio', 'SpinalTAP', 'spinaltap', 'guitar-amps'),
  ('mercuriall-audio', 'ReAxis', 'reaxis', 'guitar-amps'),

  ('audio-assault', 'Amplifikation', 'amplifikation', 'guitar-amps'),
  ('audio-assault', 'Cab Devil', 'cab-devil', 'guitar-amps'),

  ('krotos', 'Reformer Pro', 'reformer-pro', 'utilities'),
  ('krotos', 'Dehumaniser 2', 'dehumaniser-2', 'utilities'),
  ('krotos', 'Weaponiser', 'weaponiser', 'utilities'),

  ('auburn-sounds', 'Panagement', 'panagement', 'utilities'),
  ('auburn-sounds', 'Spaceship', 'spaceship', 'reverb-delay'),

  ('sample-logic', 'Cinematic Guitars', 'cinematic-guitars', 'sample-libraries'),
  ('sample-logic', 'Trailer Hits 2', 'trailer-hits-2', 'sample-libraries'),
  ('sample-logic', 'RHYTHMIC Impulse', 'rhythmic-impulse', 'sample-libraries'),

  ('aaron-venture', 'The Elements', 'the-elements', 'sample-libraries'),
  ('aaron-venture', 'True Keys', 'true-keys', 'sample-libraries'),
  ('aaron-venture', 'Hybrid Tools 2', 'hybrid-tools-2', 'sample-libraries'),

  ('precision-sound', 'Hybrid Factory', 'hybrid-factory', 'sample-libraries'),
  ('precision-sound', 'Cinematic Series', 'cinematic-series', 'sample-libraries'),

  ('in-session-audio', 'Percussive Adventures 2', 'percussive-adventures-2', 'sample-libraries'),
  ('in-session-audio', 'Ashen Choir', 'ashen-choir', 'sample-libraries'),

  ('auddict', 'Modern Scoring Strings', 'modern-scoring-strings', 'sample-libraries'),
  ('auddict', 'Rock Strings', 'rock-strings', 'sample-libraries'),

  ('chris-hein-instruments', 'Chris Hein Horns', 'chris-hein-horns', 'sample-libraries'),
  ('chris-hein-instruments', 'Chris Hein Winds', 'chris-hein-winds', 'sample-libraries'),
  ('chris-hein-instruments', 'Chris Hein Solo Strings', 'chris-hein-solo-strings', 'sample-libraries'),

  ('zero-g', 'Datafile Series', 'datafile-series', 'sample-libraries'),
  ('zero-g', 'Tao', 'tao', 'sample-libraries'),
  ('zero-g', 'Tribal Spirit', 'tribal-spirit', 'sample-libraries'),

  ('soniccouture', 'Konkrete 3', 'konkrete-3', 'sample-libraries'),
  ('soniccouture', 'Tank 3', 'tank-3', 'sample-libraries'),
  ('soniccouture', 'Attic Grand Piano', 'attic-grand-piano', 'sample-libraries'),

  ('exponential-audio', 'Stratus 3D', 'stratus-3d', 'reverb-delay'),
  ('exponential-audio', 'Nimbus', 'nimbus', 'reverb-delay'),
  ('exponential-audio', 'R4', 'r4', 'reverb-delay'),

  ('audiothing', 'Bassment', 'bassment', 'synths'),
  ('audiothing', 'Valve', 'valve', 'saturation'),
  ('audiothing', 'Outer Space', 'outer-space', 'reverb-delay'),

  ('wavesfactory', 'Cassette', 'cassette', 'saturation'),
  ('wavesfactory', 'Spring Reverb', 'spring-reverb', 'reverb-delay'),
  ('wavesfactory', 'Trombone', 'trombone', 'synths'),

  ('metric-halo', 'ChannelStrip 3', 'channelstrip-3', 'channel-strips'),
  ('metric-halo', 'MultiBand', 'multiband', 'compression'),
  ('metric-halo', 'Production Bundle', 'production-bundle', 'bundles'),

  ('cinematique-instruments', 'Fractured', 'fractured', 'synths'),
  ('cinematique-instruments', 'Fluid Piano', 'fluid-piano', 'sample-libraries'),
  ('cinematique-instruments', 'Damage', 'damage', 'sample-libraries'),

  ('rast-sound', 'Ethnic Voices', 'ethnic-voices', 'sample-libraries'),
  ('rast-sound', 'Zeynel', 'zeynel', 'sample-libraries'),
  ('rast-sound', 'Anatolian Instruments', 'anatolian-instruments', 'sample-libraries'),

  ('wusik', 'Wusikstation', 'wusikstation', 'synths'),
  ('wusik', 'Wusik String Machine', 'wusik-string-machine', 'synths'),

  ('fracture-sounds', 'Iceni Viola', 'iceni-viola', 'sample-libraries'),
  ('fracture-sounds', 'Vermeer Cello', 'vermeer-cello', 'sample-libraries'),
  ('fracture-sounds', 'String Sketches', 'string-sketches', 'sample-libraries'),

  ('big-fish-audio', 'The Black Kit', 'the-black-kit', 'sample-libraries'),
  ('big-fish-audio', 'Drums Overkill', 'drums-overkill', 'sample-libraries'),
  ('big-fish-audio', 'Vintage Instruments', 'vintage-instruments', 'sample-libraries'),

  ('hofa', 'IQ-EQ', 'iq-eq', 'eq'),
  ('hofa', 'IQ-Limiter', 'iq-limiter', 'mastering'),
  ('hofa', 'IQ-Series Complete', 'iq-series-complete', 'bundles'),

  ('vir2-instruments', 'Elite Orchestral Percussion', 'elite-orchestral-percussion', 'sample-libraries'),
  ('vir2-instruments', 'MOJO Horns Deluxe', 'mojo-horns-deluxe', 'sample-libraries'),
  ('vir2-instruments', 'Instant Orchestra', 'instant-orchestra', 'sample-libraries')
) as p(dev_slug, name, slug, category)
join public.developers d on d.slug = p.dev_slug
on conflict (developer_id, slug) do nothing;
