-- Step 18: ~570 more plugins for 3 developers already on the site (Plugin Alliance,
-- Universal Audio, MeldaProduction), whose real catalogues were far bigger than what
-- was in the database. Product names and slugs are sourced directly from each
-- developer's own store sitemap (plugin-alliance.com, uaudio.com, meldaproduction.com)
-- on 2026-09-26, so names are accurate; category assignment is best-effort from the
-- product name and may need the occasional manual correction.

insert into public.plugins (developer_id, name, slug, category)
select d.id, p.name, p.slug, p.category
from (values
  ('plugin-alliance', 'C502V', 'c502v', 'utilities'),
  ('plugin-alliance', 'Oldtimer', 'oldtimer', 'utilities'),
  ('plugin-alliance', 'Bx_boom V3', 'bx-boom-v3', 'utilities'),
  ('plugin-alliance', 'Tape Face', 'tape-face', 'saturation'),
  ('plugin-alliance', 'Bx_clipper', 'bx-clipper', 'utilities'),
  ('plugin-alliance', 'HG Q', 'hg-q', 'utilities'),
  ('plugin-alliance', 'Brainworx Bx_masterdesk Pro', 'brainworx-bx-masterdesk-pro', 'mastering'),
  ('plugin-alliance', 'Machine Head', 'machine-head', 'utilities'),
  ('plugin-alliance', 'Crystalline', 'crystalline', 'utilities'),
  ('plugin-alliance', 'SPL Big', 'spl-big', 'utilities'),
  ('plugin-alliance', 'Wavesurfer', 'wavesurfer', 'utilities'),
  ('plugin-alliance', 'Bx_refinement V3', 'bx-refinement-v3', 'utilities'),
  ('plugin-alliance', 'U2A', 'u2a', 'utilities'),
  ('plugin-alliance', 'Spatial Creator', 'spatial-creator', 'utilities'),
  ('plugin-alliance', 'Bx_xl V3', 'bx-xl-v3', 'utilities'),
  ('plugin-alliance', 'VAC Attack', 'vac-attack', 'utilities'),
  ('plugin-alliance', 'Bx_enhancer', 'bx-enhancer', 'saturation'),
  ('plugin-alliance', 'Silver Bullet Mk2', 'silver-bullet-mk2', 'utilities'),
  ('plugin-alliance', 'Bus Compressor', 'bus-compressor', 'compression'),
  ('plugin-alliance', 'Wunderlich', 'wunderlich', 'utilities'),
  ('plugin-alliance', 'Cenozoix Compressor', 'cenozoix-compressor', 'compression'),
  ('plugin-alliance', 'Xtcomp', 'xtcomp', 'utilities'),
  ('plugin-alliance', 'Bx_glue', 'bx-glue', 'utilities'),
  ('plugin-alliance', 'Hype', 'hype', 'utilities'),
  ('plugin-alliance', 'Battalion', 'battalion', 'utilities'),
  ('plugin-alliance', 'Tantra 2', 'tantra-2', 'utilities'),
  ('plugin-alliance', 'Bx_console Amek 9099', 'bx-console-amek-9099', 'channel-strips'),
  ('plugin-alliance', '50 Series', '50-series', 'utilities'),
  ('plugin-alliance', 'Big Al', 'big-al', 'utilities'),
  ('plugin-alliance', 'Mu 66', 'mu-66', 'utilities'),
  ('plugin-alliance', 'Bx_limiter True Peak', 'bx-limiter-true-peak', 'compression'),
  ('plugin-alliance', 'Se100', 'se100', 'utilities'),
  ('plugin-alliance', 'Pt100', 'pt100', 'utilities'),
  ('plugin-alliance', 'Bm60', 'bm60', 'utilities'),
  ('plugin-alliance', 'Bx_crispytuner', 'bx-crispytuner', 'utilities'),
  ('plugin-alliance', 'Sculpt', 'sculpt', 'utilities'),
  ('plugin-alliance', 'Bx_aura', 'bx-aura', 'utilities'),
  ('plugin-alliance', 'Warble', 'warble', 'utilities'),
  ('plugin-alliance', 'Sa2rate 2', 'sa2rate-2', 'utilities'),
  ('plugin-alliance', '902 De Esser', '902-de-esser', 'utilities'),
  ('plugin-alliance', 'Lisa', 'lisa', 'utilities'),
  ('plugin-alliance', 'Bx_masterdesk True Peak', 'bx-masterdesk-true-peak', 'mastering'),
  ('plugin-alliance', 'Sbc', 'sbc', 'utilities'),
  ('plugin-alliance', 'The Oven', 'the-oven', 'utilities'),
  ('plugin-alliance', 'Needlepoint', 'needlepoint', 'utilities'),
  ('plugin-alliance', 'U17', 'u17', 'utilities'),
  ('plugin-alliance', 'EQ 250', 'eq-250', 'eq'),
  ('plugin-alliance', 'Pq', 'pq', 'utilities'),
  ('plugin-alliance', 'Mastering Compressor', 'mastering-compressor', 'compression'),
  ('plugin-alliance', 'Random', 'random', 'utilities'),
  ('plugin-alliance', 'Mbc', 'mbc', 'utilities'),
  ('plugin-alliance', '69 Series', '69-series', 'utilities'),
  ('plugin-alliance', 'Kirchhoff EQ', 'kirchhoff-eq', 'eq'),
  ('plugin-alliance', 'Natalus Dsceq', 'natalus-dsceq', 'eq'),
  ('plugin-alliance', 'Bx_console Amek 200', 'bx-console-amek-200', 'channel-strips'),
  ('plugin-alliance', 'Passive Equalizer', 'passive-equalizer', 'eq'),
  ('plugin-alliance', 'Eq4 Ms', 'eq4-ms', 'eq'),
  ('plugin-alliance', 'Splat', 'splat', 'utilities'),
  ('plugin-alliance', 'Vss 2', 'vss-2', 'utilities'),
  ('plugin-alliance', 'Trinity Shaper', 'trinity-shaper', 'utilities'),
  ('plugin-alliance', 'High Flyer', 'high-flyer', 'utilities'),
  ('plugin-alliance', 'Mastering Compressor Amek', 'mastering-compressor-amek', 'compression'),
  ('plugin-alliance', 'Bx_limiter', 'bx-limiter', 'compression'),
  ('plugin-alliance', 'Bx_stereomaker', 'bx-stereomaker', 'utilities'),
  ('plugin-alliance', 'Bax EQ', 'bax-eq', 'eq'),
  ('plugin-alliance', 'Bx_hybrid V2', 'bx-hybrid-v2', 'utilities'),
  ('plugin-alliance', 'Vocal Enhancer', 'vocal-enhancer', 'saturation'),
  ('plugin-alliance', 'Vsm 3', 'vsm-3', 'utilities'),
  ('plugin-alliance', 'Gav19t', 'gav19t', 'utilities'),
  ('plugin-alliance', 'Eq2', 'eq2', 'eq'),
  ('plugin-alliance', 'Svt 3pro', 'svt-3pro', 'utilities'),
  ('plugin-alliance', 'Bx_saturator V2', 'bx-saturator-v2', 'saturation'),
  ('plugin-alliance', 'Tcl 2', 'tcl-2', 'utilities'),
  ('plugin-alliance', 'Nvelope', 'nvelope', 'utilities'),
  ('plugin-alliance', 'Flanger', 'flanger', 'utilities'),
  ('plugin-alliance', 'Bx_2098 EQ', 'bx-2098-eq', 'eq'),
  ('plugin-alliance', 'E646 Vs', 'e646-vs', 'utilities'),
  ('plugin-alliance', 'Zip', 'zip', 'utilities'),
  ('plugin-alliance', 'Bx_townhouse Buss Compressor', 'bx-townhouse-buss-compressor', 'compression'),
  ('plugin-alliance', 'E765 Rt', 'e765-rt', 'utilities'),
  ('plugin-alliance', 'Bx_opto', 'bx-opto', 'utilities'),
  ('plugin-alliance', '254e', '254e', 'utilities'),
  ('plugin-alliance', 'Bx_megadual', 'bx-megadual', 'utilities'),
  ('plugin-alliance', 'Vsc 2', 'vsc-2', 'utilities'),
  ('plugin-alliance', 'Mpressor', 'mpressor', 'utilities'),
  ('plugin-alliance', 'Bx_dyneq V2', 'bx-dyneq-v2', 'eq'),
  ('plugin-alliance', 'Drumxchanger', 'drumxchanger', 'utilities'),
  ('plugin-alliance', 'Passeq', 'passeq', 'eq'),
  ('plugin-alliance', '6x 500', '6x-500', 'utilities'),
  ('plugin-alliance', 'Bx_bassdude', 'bx-bassdude', 'utilities'),
  ('plugin-alliance', '7x 500', '7x-500', 'utilities'),
  ('plugin-alliance', 'Channelx', 'channelx', 'utilities'),
  ('plugin-alliance', 'Phils Cascade', 'phils-cascade', 'utilities'),
  ('plugin-alliance', 'Metric Ab', 'metric-ab', 'utilities'),
  ('plugin-alliance', 'Bx_console SSL 4000 G', 'bx-console-ssl-4000-g', 'channel-strips'),
  ('plugin-alliance', 'Byome', 'byome', 'utilities'),
  ('plugin-alliance', 'Iron', 'iron', 'utilities'),
  ('plugin-alliance', 'Sandman', 'sandman', 'utilities'),
  ('plugin-alliance', 'Transient Designer Plus', 'transient-designer-plus', 'utilities'),
  ('plugin-alliance', 'Magnum K', 'magnum-k', 'utilities'),
  ('plugin-alliance', 'Pex 500', 'pex-500', 'utilities'),
  ('plugin-alliance', 'EQ Ranger Plus', 'eq-ranger-plus', 'eq'),
  ('plugin-alliance', 'G8', 'g8', 'utilities'),
  ('plugin-alliance', 'Bx_paneq', 'bx-paneq', 'eq'),
  ('plugin-alliance', 'Chop Shop', 'chop-shop', 'utilities'),
  ('plugin-alliance', 'Triad', 'triad', 'utilities'),
  ('plugin-alliance', 'Hawkeye', 'hawkeye', 'utilities'),
  ('plugin-alliance', 'Thorn', 'thorn', 'utilities'),
  ('plugin-alliance', 'Bx_console Focusrite Sc', 'bx-console-focusrite-sc', 'channel-strips'),
  ('plugin-alliance', 'Bx_cleansweep Pro', 'bx-cleansweep-pro', 'utilities'),
  ('plugin-alliance', 'Dsm V3', 'dsm-v3', 'utilities'),
  ('plugin-alliance', 'Opticom Xla 3', 'opticom-xla-3', 'utilities'),
  ('plugin-alliance', 'Mc77', 'mc77', 'utilities'),
  ('plugin-alliance', 'Eq232d', 'eq232d', 'eq'),
  ('plugin-alliance', 'Lion', 'lion', 'utilities'),
  ('plugin-alliance', 'Bx_oberhausen', 'bx-oberhausen', 'utilities'),
  ('plugin-alliance', 'Vh4', 'vh4', 'utilities'),
  ('plugin-alliance', 'V 4b', 'v-4b', 'utilities'),
  ('plugin-alliance', 'Bx_rooms', 'bx-rooms', 'utilities'),
  ('plugin-alliance', 'Fault', 'fault', 'utilities'),
  ('plugin-alliance', 'Te 100', 'te-100', 'utilities'),
  ('plugin-alliance', 'B 15n', 'b-15n', 'utilities'),
  ('plugin-alliance', 'Ds 40', 'ds-40', 'utilities'),
  ('plugin-alliance', 'Svt Vr Classic', 'svt-vr-classic', 'utilities'),
  ('plugin-alliance', 'Be 100', 'be-100', 'utilities'),
  ('plugin-alliance', 'Herbert', 'herbert', 'utilities'),
  ('plugin-alliance', 'Svt Vr', 'svt-vr', 'utilities'),
  ('plugin-alliance', 'Bx_rockrack V3', 'bx-rockrack-v3', 'utilities'),
  ('plugin-alliance', 'Karacter', 'karacter', 'utilities'),
  ('plugin-alliance', 'Bx_subsynth', 'bx-subsynth', 'synths'),
  ('plugin-alliance', 'Std 1 Stereo Tapped Delay', 'std-1-stereo-tapped-delay', 'reverb-delay'),
  ('plugin-alliance', 'Mastering Compressor Class A', 'mastering-compressor-class-a', 'compression'),
  ('plugin-alliance', 'HG 2', 'hg-2', 'utilities'),
  ('plugin-alliance', 'Specops', 'specops', 'utilities'),
  ('plugin-alliance', 'Bx_rockergain100', 'bx-rockergain100', 'utilities'),
  ('plugin-alliance', 'Knifonium', 'knifonium', 'utilities'),
  ('plugin-alliance', '80 Series', '80-series', 'utilities'),
  ('plugin-alliance', 'Bx_console SSL 9000 J', 'bx-console-ssl-9000-j', 'channel-strips'),
  ('plugin-alliance', 'Savage 120', 'savage-120', 'utilities'),
  ('plugin-alliance', 'Sandman Pro', 'sandman-pro', 'utilities'),
  ('plugin-alliance', '354e', '354e', 'utilities'),
  ('plugin-alliance', 'Attacker Plus', 'attacker-plus', 'utilities'),
  ('plugin-alliance', 'Overdrive Supreme 50', 'overdrive-supreme-50', 'utilities'),
  ('plugin-alliance', 'EQ 200', 'eq-200', 'eq'),
  ('plugin-alliance', 'Lo Fi Af', 'lo-fi-af', 'utilities'),
  ('plugin-alliance', 'Mo Verb Plus', 'mo-verb-plus', 'reverb-delay'),
  ('plugin-alliance', 'Train Ii', 'train-ii', 'utilities'),
  ('plugin-alliance', 'De Verb Plus', 'de-verb-plus', 'reverb-delay'),
  ('plugin-alliance', 'Bass Mint', 'bass-mint', 'utilities'),
  ('plugin-alliance', 'Tails', 'tails', 'utilities'),
  ('plugin-alliance', 'Stage', 'stage', 'utilities'),
  ('plugin-alliance', 'Instant Delay', 'instant-delay', 'reverb-delay'),
  ('plugin-alliance', 'Character', 'character', 'utilities'),
  ('plugin-alliance', 'Bx_delay 2500', 'bx-delay-2500', 'reverb-delay'),
  ('plugin-alliance', 'Dent 2', 'dent-2', 'utilities'),
  ('plugin-alliance', 'Indent 2', 'indent-2', 'utilities'),
  ('plugin-alliance', 'Streamliner', 'streamliner', 'utilities'),
  ('plugin-alliance', 'Silo', 'silo', 'utilities'),
  ('plugin-alliance', 'Soma', 'soma', 'utilities'),
  ('plugin-alliance', 'HG 2ms', 'hg-2ms', 'utilities'),
  ('plugin-alliance', 'V76u73', 'v76u73', 'utilities'),
  ('plugin-alliance', 'Museq', 'museq', 'eq'),
  ('plugin-alliance', '800rb', '800rb', 'utilities'),
  ('plugin-alliance', 'Buxom Betty', 'buxom-betty', 'utilities'),
  ('plugin-alliance', 'Twintube', 'twintube', 'saturation'),
  ('plugin-alliance', 'De Esser Collection', 'de-esser-collection', 'bundles'),
  ('plugin-alliance', 'Nseq 2', 'nseq-2', 'eq'),
  ('plugin-alliance', 'Eq4', 'eq4', 'eq'),
  ('plugin-alliance', 'Bx_control V2', 'bx-control-v2', 'utilities'),
  ('plugin-alliance', 'Utopia', 'utopia', 'utilities'),
  ('plugin-alliance', 'Bettermaker Mastering Compressor', 'bettermaker-mastering-compressor', 'compression'),
  ('plugin-alliance', 'Lindell Audio Eq825', 'lindell-audio-eq825', 'eq'),
  ('plugin-alliance', 'Laal', 'laal', 'utilities'),
  ('plugin-alliance', 'Krotos Weaponiser Basic', 'krotos-weaponiser-basic', 'utilities'),
  ('plugin-alliance', 'Brainworx Bx_pulsar', 'brainworx-bx-pulsar', 'utilities'),
  ('plugin-alliance', 'Elysia Alpha Compressor V2', 'elysia-alpha-compressor-v2', 'compression'),
  ('plugin-alliance', 'Hitstrip', 'hitstrip', 'utilities'),
  ('plugin-alliance', 'Bde', 'bde', 'utilities'),
  ('plugin-alliance', 'Click Boom', 'click-boom', 'utilities'),
  ('plugin-alliance', 'Knocktonal', 'knocktonal', 'utilities'),
  ('plugin-alliance', 'Spread', 'spread', 'utilities'),
  ('plugin-alliance', 'Transit 2', 'transit-2', 'utilities'),
  ('plugin-alliance', 'Dehumaniser 2', 'dehumaniser-2', 'utilities'),
  ('plugin-alliance', 'Vitalizer Mk3 T', 'vitalizer-mk3-t', 'utilities'),
  ('plugin-alliance', 'Perfection', 'perfection', 'utilities'),
  ('plugin-alliance', 'Oberheim Ob X', 'oberheim-ob-x', 'utilities'),
  ('plugin-alliance', 'Icondrum', 'icondrum', 'utilities'),
  ('plugin-alliance', 'Vsm Iv', 'vsm-iv', 'utilities'),
  ('plugin-alliance', 'Minimonsta2', 'minimonsta2', 'utilities'),
  ('plugin-alliance', 'Imposcar3', 'imposcar3', 'utilities'),
  ('plugin-alliance', 'Axxess', 'axxess', 'utilities'),
  ('plugin-alliance', '7deadlysnares', '7deadlysnares', 'utilities'),
  ('plugin-alliance', 'Lunchtable', 'lunchtable', 'utilities'),
  ('plugin-alliance', 'Reformer Pro', 'reformer-pro', 'utilities'),
  ('plugin-alliance', 'Smooth Operator Pro', 'smooth-operator-pro', 'utilities'),
  ('plugin-alliance', 'Comeback Kid', 'comeback-kid', 'utilities'),
  ('plugin-alliance', 'Beatfader', 'beatfader', 'utilities'),
  ('plugin-alliance', 'Cheat Code', 'cheat-code', 'utilities'),
  ('plugin-alliance', 'Optomax', 'optomax', 'utilities'),
  ('plugin-alliance', 'Spaced Out', 'spaced-out', 'utilities'),
  ('plugin-alliance', 'Tekno', 'tekno', 'utilities'),
  ('plugin-alliance', 'Random Metal', 'random-metal', 'utilities'),
  ('plugin-alliance', 'Gforce Software Oberheim Dmx', 'gforce-software-oberheim-dmx', 'utilities'),
  ('plugin-alliance', 'Ocelot Limiter', 'ocelot-limiter', 'compression'),
  ('plugin-alliance', 'Ocelot Clipper', 'ocelot-clipper', 'utilities'),
  ('plugin-alliance', 'Ocelot Bundle', 'ocelot-bundle', 'bundles'),
  ('plugin-alliance', 'Rz062', 'rz062', 'utilities'),
  ('plugin-alliance', 'Igniter', 'igniter', 'utilities'),
  ('plugin-alliance', 'Humanoid', 'humanoid', 'utilities'),
  ('plugin-alliance', 'Ba 1', 'ba-1', 'utilities'),
  ('plugin-alliance', 'Bx_tonebox', 'bx-tonebox', 'utilities'),
  ('plugin-alliance', 'Novation Bass Station', 'novation-bass-station', 'utilities'),
  ('plugin-alliance', 'Oberheim Tvs Pro', 'oberheim-tvs-pro', 'utilities'),
  ('plugin-alliance', 'Map', 'map', 'utilities'),
  ('plugin-alliance', 'Oddity3', 'oddity3', 'utilities'),
  ('plugin-alliance', 'Limiter', 'limiter', 'compression'),
  ('plugin-alliance', 'Expose 2', 'expose-2', 'utilities'),
  ('plugin-alliance', 'Faster Master', 'faster-master', 'mastering'),
  ('plugin-alliance', 'Levels', 'levels', 'utilities'),
  ('plugin-alliance', 'Bassroom', 'bassroom', 'utilities'),
  ('plugin-alliance', 'Mixroom', 'mixroom', 'utilities'),
  ('plugin-alliance', 'Fuser', 'fuser', 'utilities'),
  ('plugin-alliance', 'Ocelot Octaver', 'ocelot-octaver', 'utilities'),
  ('plugin-alliance', 'Ocelot Upmixer', 'ocelot-upmixer', 'utilities'),
  ('plugin-alliance', 'Reso', 'reso', 'utilities'),
  ('plugin-alliance', 'Reference', 'reference', 'utilities'),
  ('plugin-alliance', 'Animate', 'animate', 'utilities'),
  ('plugin-alliance', 'Grainferno', 'grainferno', 'utilities'),
  ('plugin-alliance', 'Stereovault', 'stereovault', 'utilities'),
  ('plugin-alliance', 'Complete Bundle', 'complete-bundle', 'bundles'),
  ('universal-audio', 'Moog Minimoog', 'moog-minimoog', 'synths'),
  ('universal-audio', '6176 Vintage Channel Strip', '6176-vintage-channel-strip', 'channel-strips'),
  ('universal-audio', 'Neve Complete Bundle', 'neve-complete-bundle', 'bundles'),
  ('universal-audio', 'Lion 68 Super Lead Amp', 'lion-68-super-lead-amp', 'guitar-amps'),
  ('universal-audio', 'Thermionic Culture Vulture', 'thermionic-culture-vulture', 'saturation'),
  ('universal-audio', '1176 Collection', '1176-collection', 'bundles'),
  ('universal-audio', 'ADA Flanger', 'ada-flanger', 'utilities'),
  ('universal-audio', 'ADA Std 1 Stereo Tapped Delay', 'ada-std-1-stereo-tapped-delay', 'reverb-delay'),
  ('universal-audio', 'AKG bx_20 Reverb', 'akg-bx-20-reverb', 'reverb-delay'),
  ('universal-audio', 'Ampeg B15n', 'ampeg-b15n', 'guitar-amps'),
  ('universal-audio', 'Ampeg Svt 3 Pro', 'ampeg-svt-3-pro', 'guitar-amps'),
  ('universal-audio', 'Ampeg Svt Vr', 'ampeg-svt-vr', 'guitar-amps'),
  ('universal-audio', 'Ams Dmx Digital Delay Pitch Shifter', 'ams-dmx-digital-delay-pitch-shifter', 'reverb-delay'),
  ('universal-audio', 'Ams Neve Dfc Channel Strip', 'ams-neve-dfc-channel-strip', 'channel-strips'),
  ('universal-audio', 'API 2500 Bus Compressor', 'api-2500-bus-compressor', 'compression'),
  ('universal-audio', 'API 500 Series EQ Collection', 'api-500-series-eq-collection', 'eq'),
  ('universal-audio', 'API Preamp', 'api-preamp', 'channel-strips'),
  ('universal-audio', 'API Summing', 'api-summing', 'utilities'),
  ('universal-audio', 'API Vision Channel Strip Collection', 'api-vision-channel-strip-collection', 'channel-strips'),
  ('universal-audio', 'Avalon VT 737 Tube Channel Strip', 'avalon-vt-737-tube-channel-strip', 'channel-strips'),
  ('universal-audio', 'Brainworx bx_Digital3', 'brainworx-bx-digital3', 'utilities'),
  ('universal-audio', 'Brainworx bx_Masterdesk', 'brainworx-bx-masterdesk', 'mastering'),
  ('universal-audio', 'Brainworx bx_Masterdesk Classic', 'brainworx-bx-masterdesk-classic', 'mastering'),
  ('universal-audio', 'Brainworx bx_Subsynth', 'brainworx-bx-subsynth', 'synths'),
  ('universal-audio', 'Brigade Chorus', 'brigade-chorus', 'utilities'),
  ('universal-audio', 'bx_Refinement', 'bx-refinement', 'utilities'),
  ('universal-audio', 'bx_Saturator V2', 'bx-saturator-v2', 'saturation'),
  ('universal-audio', 'C Suite C Axe Guitar Noise Suppressor', 'c-suite-c-axe-guitar-noise-suppressor', 'guitar-amps'),
  ('universal-audio', 'C Suite C Max Limiter', 'c-suite-c-max-limiter', 'compression'),
  ('universal-audio', 'C Vox Noise Reduction', 'c-vox-noise-reduction', 'utilities'),
  ('universal-audio', 'Cambridge EQ', 'cambridge-eq', 'eq'),
  ('universal-audio', 'Capitol Mastering Compressor', 'capitol-mastering-compressor', 'compression'),
  ('universal-audio', 'Century Tube Channel Strip', 'century-tube-channel-strip', 'channel-strips'),
  ('universal-audio', 'Chandler Gav 19t Guitar Amp', 'chandler-gav-19t-guitar-amp', 'guitar-amps'),
  ('universal-audio', 'Chandler Limited Curve Bender', 'chandler-limited-curve-bender', 'utilities'),
  ('universal-audio', 'Chandler Limited Zener Limiter', 'chandler-limited-zener-limiter', 'compression'),
  ('universal-audio', 'Cooper Time Cube', 'cooper-time-cube', 'utilities'),
  ('universal-audio', 'Dangerous Bax EQ', 'dangerous-bax-eq', 'eq'),
  ('universal-audio', 'Dbx 160', 'dbx-160', 'utilities'),
  ('universal-audio', 'Diezel Herbert Amplifier', 'diezel-herbert-amplifier', 'guitar-amps'),
  ('universal-audio', 'Diezel Vh4 Amplifier', 'diezel-vh4-amplifier', 'guitar-amps'),
  ('universal-audio', 'Dreamverb', 'dreamverb', 'reverb-delay'),
  ('universal-audio', 'Dytronics Cyclosonic Panner', 'dytronics-cyclosonic-panner', 'utilities'),
  ('universal-audio', 'Dytronics Tri Stereo Chorus', 'dytronics-tri-stereo-chorus', 'utilities'),
  ('universal-audio', 'Eden Wt800 Bass Amplifier', 'eden-wt800-bass-amplifier', 'guitar-amps'),
  ('universal-audio', 'Electra 88 Vintage Keyboard Studio', 'electra-88-vintage-keyboard-studio', 'utilities'),
  ('universal-audio', 'Elysia Mpressor', 'elysia-mpressor', 'utilities'),
  ('universal-audio', 'Empirical Labs El8 Distressor Compressor', 'empirical-labs-el8-distressor-compressor', 'compression'),
  ('universal-audio', 'Engl E646 Vs', 'engl-e646-vs', 'utilities'),
  ('universal-audio', 'Engl E765 Rt', 'engl-e765-rt', 'utilities'),
  ('universal-audio', 'Engl Savage 120 Amplifier', 'engl-savage-120-amplifier', 'guitar-amps'),
  ('universal-audio', 'Ep 34', 'ep-34', 'utilities'),
  ('universal-audio', 'Eventide H910', 'eventide-h910', 'utilities'),
  ('universal-audio', 'Fatso', 'fatso', 'utilities'),
  ('universal-audio', 'Fender 55 Dlx', 'fender-55-dlx', 'utilities'),
  ('universal-audio', 'Friedman Amplifiers Plug In Collection', 'friedman-amplifiers-plug-in-collection', 'guitar-amps'),
  ('universal-audio', 'Friedman Buxom Betty', 'friedman-buxom-betty', 'utilities'),
  ('universal-audio', 'Fuchs Overdrive Amp Plug In', 'fuchs-overdrive-amp-plug-in', 'guitar-amps'),
  ('universal-audio', 'Fuchs Train Amp', 'fuchs-train-amp', 'guitar-amps'),
  ('universal-audio', 'Galaxy Tape Echo', 'galaxy-tape-echo', 'reverb-delay'),
  ('universal-audio', 'Gallien Krueger 800rb Bass Amp', 'gallien-krueger-800rb-bass-amp', 'guitar-amps'),
  ('universal-audio', 'Harrison 32c', 'harrison-32c', 'utilities'),
  ('universal-audio', 'Helios Type 69 Preamp EQ', 'helios-type-69-preamp-eq', 'channel-strips'),
  ('universal-audio', 'Hitsville EQ Collection', 'hitsville-eq-collection', 'eq'),
  ('universal-audio', 'Hitsville Reverb Chambers', 'hitsville-reverb-chambers', 'reverb-delay'),
  ('universal-audio', 'K Stereo Ambience Recovery', 'k-stereo-ambience-recovery', 'utilities'),
  ('universal-audio', 'Korg Sdd 3000 Digital Delay', 'korg-sdd-3000-digital-delay', 'reverb-delay'),
  ('universal-audio', 'Lexicon 224', 'lexicon-224', 'utilities'),
  ('universal-audio', 'Lexicon 480l Digital Reverb Effects', 'lexicon-480l-digital-reverb-effects', 'reverb-delay'),
  ('universal-audio', 'Little Labs Ibp', 'little-labs-ibp', 'utilities'),
  ('universal-audio', 'Manley Tube Preamp', 'manley-tube-preamp', 'channel-strips'),
  ('universal-audio', 'Manley Variable Mu', 'manley-variable-mu', 'utilities'),
  ('universal-audio', 'Manley Voxbox', 'manley-voxbox', 'utilities'),
  ('universal-audio', 'Marshall Bluesbreaker', 'marshall-bluesbreaker', 'utilities'),
  ('universal-audio', 'Marshall Jmp2203', 'marshall-jmp2203', 'utilities'),
  ('universal-audio', 'Marshall Plexi', 'marshall-plexi', 'utilities'),
  ('universal-audio', 'Marshall Silver Jubilee', 'marshall-silver-jubilee', 'utilities'),
  ('universal-audio', 'Massenburg Mdweq5', 'massenburg-mdweq5', 'eq'),
  ('universal-audio', 'Millennia Nseq 2', 'millennia-nseq-2', 'eq'),
  ('universal-audio', 'Moog Multimode Filter Xl Collection', 'moog-multimode-filter-xl-collection', 'synths'),
  ('universal-audio', 'Mxr Flanger Doubler', 'mxr-flanger-doubler', 'utilities'),
  ('universal-audio', 'Neve 1073 Collection', 'neve-1073-collection', 'bundles'),
  ('universal-audio', 'Neve 1081', 'neve-1081', 'utilities'),
  ('universal-audio', 'Neve 1084 Preamp EQ', 'neve-1084-preamp-eq', 'channel-strips'),
  ('universal-audio', 'Neve 31102', 'neve-31102', 'utilities'),
  ('universal-audio', 'Neve 88rs Collection', 'neve-88rs-collection', 'bundles'),
  ('universal-audio', 'Neve Dynamics Collection', 'neve-dynamics-collection', 'compression'),
  ('universal-audio', 'Neve Preamp', 'neve-preamp', 'channel-strips'),
  ('universal-audio', 'Neve Summing', 'neve-summing', 'utilities'),
  ('universal-audio', 'Opal Morphing Synthesizer', 'opal-morphing-synthesizer', 'synths'),
  ('universal-audio', 'Oxford Envolution', 'oxford-envolution', 'utilities'),
  ('universal-audio', 'Oxford EQ', 'oxford-eq', 'eq'),
  ('universal-audio', 'Oxford Inflator', 'oxford-inflator', 'utilities'),
  ('universal-audio', 'Oxide Tape Recorder', 'oxide-tape-recorder', 'saturation'),
  ('universal-audio', 'Polymax Synth', 'polymax-synth', 'synths'),
  ('universal-audio', 'Precision Buss Compressor', 'precision-buss-compressor', 'compression'),
  ('universal-audio', 'Precision De Esser', 'precision-de-esser', 'utilities'),
  ('universal-audio', 'Precision Enhancer Hz', 'precision-enhancer-hz', 'saturation'),
  ('universal-audio', 'Precision Enhancer Khz', 'precision-enhancer-khz', 'saturation'),
  ('universal-audio', 'Precision EQ', 'precision-eq', 'eq'),
  ('universal-audio', 'Precision Limiter', 'precision-limiter', 'compression'),
  ('universal-audio', 'Precision Maximizer', 'precision-maximizer', 'mastering'),
  ('universal-audio', 'Precision Multiband', 'precision-multiband', 'utilities'),
  ('universal-audio', 'Pure Plate Reverb', 'pure-plate-reverb', 'reverb-delay'),
  ('universal-audio', 'Ravel', 'ravel', 'utilities'),
  ('universal-audio', 'Rmx 16 Expanded', 'rmx-16-expanded', 'utilities'),
  ('universal-audio', 'Softube Vocoder', 'softube-vocoder', 'saturation'),
  ('universal-audio', 'Sonnox Oxford Dynamic EQ', 'sonnox-oxford-dynamic-eq', 'eq'),
  ('universal-audio', 'Sonnox Oxford Limiter V2', 'sonnox-oxford-limiter-v2', 'compression'),
  ('universal-audio', 'Sonnox Oxford Supresser Ds', 'sonnox-oxford-supresser-ds', 'utilities'),
  ('universal-audio', 'Sound Machine Wood Works', 'sound-machine-wood-works', 'utilities'),
  ('universal-audio', 'Spitfire Chamber Strings Luna Edition', 'spitfire-chamber-strings-luna-edition', 'utilities'),
  ('universal-audio', 'Spitfire Symphonic Brass Luna Edition', 'spitfire-symphonic-brass-luna-edition', 'utilities'),
  ('universal-audio', 'Spitfire Symphonic Woodwinds Luna Edition', 'spitfire-symphonic-woodwinds-luna-edition', 'utilities'),
  ('universal-audio', 'SPL Transient Designer', 'spl-transient-designer', 'utilities'),
  ('universal-audio', 'Studer A800 Tape Recorder', 'studer-a800-tape-recorder', 'saturation'),
  ('universal-audio', 'Studio D Chorus', 'studio-d-chorus', 'utilities'),
  ('universal-audio', 'Suhr Pt100 Amplifier', 'suhr-pt100-amplifier', 'guitar-amps'),
  ('universal-audio', 'Suhr Se100 Amplifier', 'suhr-se100-amplifier', 'guitar-amps'),
  ('universal-audio', 'Summit Tla Compressor', 'summit-tla-compressor', 'compression'),
  ('universal-audio', 'Tonelux Tilt EQ', 'tonelux-tilt-eq', 'eq'),
  ('universal-audio', 'Trident A Range', 'trident-a-range', 'utilities'),
  ('universal-audio', 'Tube Tech Cl 1b Mkii Compressor', 'tube-tech-cl-1b-mkii-compressor', 'compression'),
  ('universal-audio', 'Tube Tech EQ Collection', 'tube-tech-eq-collection', 'eq'),
  ('universal-audio', 'Ua Tube Compressor Collection', 'ua-tube-compressor-collection', 'compression'),
  ('universal-audio', 'Uad La 3a', 'uad-la-3a', 'utilities'),
  ('universal-audio', 'Uad Oto Biscuit Effects Plug In', 'uad-oto-biscuit-effects-plug-in', 'utilities'),
  ('universal-audio', 'Uad Sound City Studios Plug In', 'uad-sound-city-studios-plug-in', 'utilities'),
  ('universal-audio', 'V76 Preamplifier', 'v76-preamplifier', 'channel-strips'),
  ('universal-audio', 'Valley People Dyna Mite', 'valley-people-dyna-mite', 'utilities'),
  ('universal-audio', 'Vsc 2 Compressor', 'vsc-2-compressor', 'compression'),
  ('universal-audio', 'Waterfall B3', 'waterfall-b3', 'utilities'),
  ('universal-audio', 'Waterfall Rotary Speaker', 'waterfall-rotary-speaker', 'utilities'),
  ('universal-audio', '1176ln Classic Limiting Amplifier', '1176ln-classic-limiting-amplifier', 'guitar-amps'),
  ('universal-audio', '4 710d Four Channel Tone Blending Mic Preamp', '4-710d-four-channel-tone-blending-mic-preamp', 'channel-strips'),
  ('universal-audio', 'La 610 Mkii Classic Tube Recording Channel', 'la-610-mkii-classic-tube-recording-channel', 'saturation'),
  ('universal-audio', 'Solo 610 Classic Tube Preamplifier Di Box', 'solo-610-classic-tube-preamplifier-di-box', 'channel-strips'),
  ('universal-audio', 'Teletronix La 2a Classic Leveling Amplifier', 'teletronix-la-2a-classic-leveling-amplifier', 'guitar-amps'),
  ('universal-audio', '1176 Studio Compressor Pedal', '1176-studio-compressor-pedal', 'compression'),
  ('universal-audio', 'Astra Modulation Machine', 'astra-modulation-machine', 'utilities'),
  ('universal-audio', 'Brigade Chorus Vibrato', 'brigade-chorus-vibrato', 'utilities'),
  ('universal-audio', 'Del Verb Ambience Companion', 'del-verb-ambience-companion', 'reverb-delay'),
  ('universal-audio', 'Dream 65 Reverb Amplifier', 'dream-65-reverb-amplifier', 'reverb-delay'),
  ('universal-audio', 'Evermore Studio Reverb', 'evermore-studio-reverb', 'reverb-delay'),
  ('universal-audio', 'Flow Vintage Tremolo', 'flow-vintage-tremolo', 'utilities'),
  ('universal-audio', 'Galaxy 74 Tape Echo Reverb', 'galaxy-74-tape-echo-reverb', 'reverb-delay'),
  ('universal-audio', 'Golden Reverberator', 'golden-reverberator', 'reverb-delay'),
  ('universal-audio', 'Heavenly Plate Reverb', 'heavenly-plate-reverb', 'reverb-delay'),
  ('universal-audio', 'Max Preamp Dual Compressor', 'max-preamp-dual-compressor', 'channel-strips'),
  ('universal-audio', 'Orion Tape Echo', 'orion-tape-echo', 'reverb-delay'),
  ('universal-audio', 'Ox Stomp Dynamic Speaker Emulator', 'ox-stomp-dynamic-speaker-emulator', 'utilities'),
  ('universal-audio', 'Ruby 63 Top Boost Amplifier', 'ruby-63-top-boost-amplifier', 'guitar-amps'),
  ('universal-audio', 'Starlight Echo Station', 'starlight-echo-station', 'reverb-delay'),
  ('universal-audio', 'Teletronix La 2a Studio Compressor', 'teletronix-la-2a-studio-compressor', 'compression'),
  ('universal-audio', 'Woodrow 55 Instrument Amplifier', 'woodrow-55-instrument-amplifier', 'guitar-amps'),
  ('universal-audio', 'Ox Amp Top Box', 'ox-amp-top-box', 'guitar-amps'),
  ('universal-audio', 'Ua Bock 167', 'ua-bock-167', 'utilities'),
  ('universal-audio', 'Ua Bock 187', 'ua-bock-187', 'utilities'),
  ('universal-audio', 'Ua Bock 251', 'ua-bock-251', 'utilities'),
  ('universal-audio', 'API Vision Console Emulation Bundle', 'api-vision-console-emulation-bundle', 'channel-strips'),
  ('universal-audio', 'SSL 4000 Series Bundle', 'ssl-4000-series-bundle', 'bundles'),
  ('universal-audio', 'Distortion Essentials Bundle', 'distortion-essentials-bundle', 'bundles'),
  ('universal-audio', 'Luna Spitfire Bundle', 'luna-spitfire-bundle', 'bundles'),
  ('universal-audio', 'Marshall Legends Bundle', 'marshall-legends-bundle', 'bundles'),
  ('universal-audio', 'Softube Amp Room Bundle', 'softube-amp-room-bundle', 'guitar-amps'),
  ('universal-audio', 'Uad Custom 10 Bundle', 'uad-custom-10-bundle', 'bundles'),
  ('universal-audio', 'Anti 1992 High Gain Amp', 'anti-1992-high-gain-amp', 'guitar-amps'),
  ('universal-audio', 'Knuckles 92 Dual Rec Amplifier', 'knuckles-92-dual-rec-amplifier', 'guitar-amps'),
  ('universal-audio', 'Enigmatic 82 Overdrive Special Amp', 'enigmatic-82-overdrive-special-amp', 'guitar-amps'),
  ('universal-audio', 'La6176 Signature Channel Strip', 'la6176-signature-channel-strip', 'channel-strips'),
  ('universal-audio', 'Analog Tape Bundle', 'analog-tape-bundle', 'saturation'),
  ('universal-audio', 'Uad Guitar Amp Bundle', 'uad-guitar-amp-bundle', 'guitar-amps'),
  ('universal-audio', 'Topline Vocal Suite', 'topline-vocal-suite', 'utilities'),
  ('universal-audio', 'SSL 4000 E Series Channel Strip', 'ssl-4000-e-series-channel-strip', 'channel-strips'),
  ('universal-audio', 'Woodrow 55 Instrument', 'woodrow-55-instrument', 'utilities'),
  ('universal-audio', 'Ua 1176 Fet', 'ua-1176-fet', 'utilities'),
  ('universal-audio', 'Dream 65 Reverb', 'dream-65-reverb', 'reverb-delay'),
  ('universal-audio', 'Lion 68 Super Lead', 'lion-68-super-lead', 'utilities'),
  ('universal-audio', 'Uad Select 10 Bundle', 'uad-select-10-bundle', 'bundles'),
  ('universal-audio', 'SSL 4000 G Series Bus Compressor', 'ssl-4000-g-series-bus-compressor', 'compression'),
  ('universal-audio', 'Ruby 63 Top Boost', 'ruby-63-top-boost', 'utilities'),
  ('universal-audio', 'Teletronix La 2a Tube Compressor', 'teletronix-la-2a-tube-compressor', 'compression'),
  ('universal-audio', 'Anthem Analog Synthesizer', 'anthem-analog-synthesizer', 'synths'),
  ('universal-audio', 'Showtime 64 Tube Amp', 'showtime-64-tube-amp', 'guitar-amps'),
  ('universal-audio', 'Uad Pro Vocal Bundle', 'uad-pro-vocal-bundle', 'bundles'),
  ('universal-audio', 'Uad Guitar Bundle', 'uad-guitar-bundle', 'guitar-amps'),
  ('universal-audio', 'Uad Classic Keys And Synths Bundle', 'uad-classic-keys-and-synths-bundle', 'synths'),
  ('universal-audio', 'A Type Multiband Dynamic Enhancer', 'a-type-multiband-dynamic-enhancer', 'saturation'),
  ('universal-audio', 'Shadow Hills Mastering Compressor Class A', 'shadow-hills-mastering-compressor-class-a', 'compression'),
  ('universal-audio', 'Maag Eq4 Ms', 'maag-eq4-ms', 'eq'),
  ('universal-audio', 'Little Labs Voice Of God', 'little-labs-voice-of-god', 'utilities'),
  ('universal-audio', '610 Collection', '610-collection', 'bundles'),
  ('universal-audio', 'Paradise Guitar Studio', 'paradise-guitar-studio', 'guitar-amps'),
  ('universal-audio', 'Ocean Way Studios Deluxe', 'ocean-way-studios-deluxe', 'utilities'),
  ('universal-audio', 'Uad Mix Tape 10', 'uad-mix-tape-10', 'saturation'),
  ('universal-audio', 'SPL Vitalizer Mk3 T', 'spl-vitalizer-mk3-t', 'utilities'),
  ('universal-audio', 'Elysia Alpha Compressor V2', 'elysia-alpha-compressor-v2', 'compression'),
  ('universal-audio', 'Uad Ultimate 14', 'uad-ultimate-14', 'utilities'),
  ('universal-audio', 'Uad Complete 4', 'uad-complete-4', 'bundles'),
  ('universal-audio', 'Enigmatic 82 Overdrive Special', 'enigmatic-82-overdrive-special', 'utilities'),
  ('universal-audio', 'Vibe Analog Machines', 'vibe-analog-machines', 'utilities'),
  ('universal-audio', 'Vibe Analog Machines Essentials', 'vibe-analog-machines-essentials', 'utilities'),
  ('universal-audio', 'Emt 250', 'emt-250', 'utilities'),
  ('universal-audio', 'Emt 140', 'emt-140', 'utilities'),
  ('universal-audio', 'Topline Vocal Tune', 'topline-vocal-tune', 'utilities'),
  ('universal-audio', 'Black Box HG 2', 'black-box-hg-2', 'utilities'),
  ('universal-audio', 'Uad Guitar Mix Tape', 'uad-guitar-mix-tape', 'guitar-amps'),
  ('universal-audio', 'Uad Vocal Mix Tape', 'uad-vocal-mix-tape', 'saturation'),
  ('universal-audio', 'Uad Compressor All Stars Mix Tape', 'uad-compressor-all-stars-mix-tape', 'compression'),
  ('universal-audio', 'Uad Hip Hop Mix Tape', 'uad-hip-hop-mix-tape', 'saturation'),
  ('universal-audio', 'Uad Classic Tone EQ Mix Tape', 'uad-classic-tone-eq-mix-tape', 'eq'),
  ('universal-audio', 'Uad Carlos De La Garza Mix Tape', 'uad-carlos-de-la-garza-mix-tape', 'saturation'),
  ('universal-audio', 'Elysia Karacter', 'elysia-karacter', 'utilities'),
  ('universal-audio', 'Uad Native Pro Bundle', 'uad-native-pro-bundle', 'bundles'),
  ('universal-audio', 'Uad Native Classics Bundle', 'uad-native-classics-bundle', 'bundles'),
  ('universal-audio', 'Uad Native Studio Bundle', 'uad-native-studio-bundle', 'bundles'),
  ('universal-audio', 'Uad Native Producer Bundle', 'uad-native-producer-bundle', 'bundles'),
  ('universal-audio', 'Luna Studio', 'luna-studio', 'utilities'),
  ('universal-audio', 'Uad Will Yip Mix Tape', 'uad-will-yip-mix-tape', 'saturation'),
  ('universal-audio', 'Luna Studio Uad Native Pro Bundle', 'luna-studio-uad-native-pro-bundle', 'bundles'),
  ('meldaproduction', 'MAGC', 'magc', 'utilities'),
  ('meldaproduction', 'MAmp', 'mamp', 'guitar-amps'),
  ('meldaproduction', 'MAutoDynamicEq', 'mautodynamiceq', 'eq'),
  ('meldaproduction', 'MAutoEqualizer', 'mautoequalizer', 'eq'),
  ('meldaproduction', 'MAutoStereoFix', 'mautostereofix', 'utilities'),
  ('meldaproduction', 'MAutoVolume', 'mautovolume', 'utilities'),
  ('meldaproduction', 'MAutopan', 'mautopan', 'utilities'),
  ('meldaproduction', 'MAutopanMB', 'mautopanmb', 'utilities'),
  ('meldaproduction', 'MBandPass', 'mbandpass', 'utilities'),
  ('meldaproduction', 'MBassador', 'mbassador', 'utilities'),
  ('meldaproduction', 'MBitFun', 'mbitfun', 'utilities'),
  ('meldaproduction', 'MBitFunMB', 'mbitfunmb', 'utilities'),
  ('meldaproduction', 'MCCGenerator', 'mccgenerator', 'utilities'),
  ('meldaproduction', 'MCabinet', 'mcabinet', 'guitar-amps'),
  ('meldaproduction', 'MCenter', 'mcenter', 'utilities'),
  ('meldaproduction', 'MChannelMatrix', 'mchannelmatrix', 'utilities'),
  ('meldaproduction', 'MCharacter', 'mcharacter', 'utilities'),
  ('meldaproduction', 'MChorusMB', 'mchorusmb', 'utilities'),
  ('meldaproduction', 'MComb', 'mcomb', 'utilities'),
  ('meldaproduction', 'MCombMB', 'mcombmb', 'utilities'),
  ('meldaproduction', 'MCompare', 'mcompare', 'utilities'),
  ('meldaproduction', 'MConvolutionEZ', 'mconvolutionez', 'utilities'),
  ('meldaproduction', 'MConvolutionMB', 'mconvolutionmb', 'utilities'),
  ('meldaproduction', 'MCreativeFXBundle', 'mcreativefxbundle', 'bundles'),
  ('meldaproduction', 'MDelay', 'mdelay', 'reverb-delay'),
  ('meldaproduction', 'MDelayMB', 'mdelaymb', 'reverb-delay'),
  ('meldaproduction', 'MDistortionMB', 'mdistortionmb', 'utilities'),
  ('meldaproduction', 'MDoubleTracker', 'mdoubletracker', 'utilities'),
  ('meldaproduction', 'MDrumCleaner', 'mdrumcleaner', 'utilities'),
  ('meldaproduction', 'MDrumEnhancer', 'mdrumenhancer', 'saturation'),
  ('meldaproduction', 'MDrumLeveler', 'mdrumleveler', 'compression'),
  ('meldaproduction', 'MDrumReplacer', 'mdrumreplacer', 'utilities'),
  ('meldaproduction', 'MDrumStrip', 'mdrumstrip', 'utilities'),
  ('meldaproduction', 'MDynamics', 'mdynamics', 'compression'),
  ('meldaproduction', 'MDynamicsMB', 'mdynamicsmb', 'compression'),
  ('meldaproduction', 'MEqualizerLP', 'mequalizerlp', 'eq'),
  ('meldaproduction', 'MEssentialsFXBundle', 'messentialsfxbundle', 'bundles'),
  ('meldaproduction', 'MFilter', 'mfilter', 'utilities'),
  ('meldaproduction', 'MFlanger', 'mflanger', 'utilities'),
  ('meldaproduction', 'MFlangerMB', 'mflangermb', 'utilities'),
  ('meldaproduction', 'MFreeFXBundle', 'mfreefxbundle', 'bundles'),
  ('meldaproduction', 'MFreeformAnalogEq', 'mfreeformanalogeq', 'eq'),
  ('meldaproduction', 'MFreeformEqualizer', 'mfreeformequalizer', 'eq'),
  ('meldaproduction', 'MFreeformPhase', 'mfreeformphase', 'utilities'),
  ('meldaproduction', 'MFreqShifter', 'mfreqshifter', 'eq'),
  ('meldaproduction', 'MFreqShifterMB', 'mfreqshiftermb', 'eq'),
  ('meldaproduction', 'MGranularMB', 'mgranularmb', 'utilities'),
  ('meldaproduction', 'MGuitarArchitect', 'mguitararchitect', 'guitar-amps'),
  ('meldaproduction', 'MHarmonizerMB', 'mharmonizermb', 'utilities'),
  ('meldaproduction', 'MLimiterMB', 'mlimitermb', 'compression'),
  ('meldaproduction', 'MLimiterX', 'mlimiterx', 'compression'),
  ('meldaproduction', 'MLoudnessAnalyzer', 'mloudnessanalyzer', 'mastering'),
  ('meldaproduction', 'MMasteringFXBundle', 'mmasteringfxbundle', 'mastering'),
  ('meldaproduction', 'MMatcher', 'mmatcher', 'utilities'),
  ('meldaproduction', 'MMetronome', 'mmetronome', 'utilities'),
  ('meldaproduction', 'MMicSim', 'mmicsim', 'utilities'),
  ('meldaproduction', 'MMixingFXBundle', 'mmixingfxbundle', 'bundles'),
  ('meldaproduction', 'MModernCompressor', 'mmoderncompressor', 'compression'),
  ('meldaproduction', 'MMorph', 'mmorph', 'utilities'),
  ('meldaproduction', 'MMultiAnalyzer', 'mmultianalyzer', 'utilities'),
  ('meldaproduction', 'MNoiseGenerator', 'mnoisegenerator', 'utilities'),
  ('meldaproduction', 'MNotepad', 'mnotepad', 'utilities'),
  ('meldaproduction', 'MOscillator', 'moscillator', 'synths'),
  ('meldaproduction', 'MOscilloscope', 'moscilloscope', 'utilities'),
  ('meldaproduction', 'MPhaser', 'mphaser', 'utilities'),
  ('meldaproduction', 'MPhaserMB', 'mphasermb', 'utilities'),
  ('meldaproduction', 'MPhatik', 'mphatik', 'utilities'),
  ('meldaproduction', 'MPolySaturator', 'mpolysaturator', 'saturation'),
  ('meldaproduction', 'MPowerSynth', 'mpowersynth', 'synths'),
  ('meldaproduction', 'MRatio', 'mratio', 'utilities'),
  ('meldaproduction', 'MRatioMB', 'mratiomb', 'utilities'),
  ('meldaproduction', 'MRecorder', 'mrecorder', 'utilities'),
  ('meldaproduction', 'MReverb', 'mreverb', 'reverb-delay'),
  ('meldaproduction', 'MReverbMB', 'mreverbmb', 'reverb-delay'),
  ('meldaproduction', 'MRhythmizer', 'mrhythmizer', 'utilities'),
  ('meldaproduction', 'MRhythmizerMB', 'mrhythmizermb', 'utilities'),
  ('meldaproduction', 'MRingModulator', 'mringmodulator', 'utilities'),
  ('meldaproduction', 'MRingModulatorMB', 'mringmodulatormb', 'utilities'),
  ('meldaproduction', 'MRotary', 'mrotary', 'utilities'),
  ('meldaproduction', 'MSaturatorMB', 'msaturatormb', 'saturation'),
  ('meldaproduction', 'MSoundFactoryEssentials', 'msoundfactoryessentials', 'utilities'),
  ('meldaproduction', 'MSoundFactoryLE', 'msoundfactoryle', 'utilities'),
  ('meldaproduction', 'MSoundFactoryPlayer', 'msoundfactoryplayer', 'utilities'),
  ('meldaproduction', 'MSpectralDelay', 'mspectraldelay', 'reverb-delay'),
  ('meldaproduction', 'MSpectralDynamics', 'mspectraldynamics', 'compression'),
  ('meldaproduction', 'MSpectralDynamicsLE', 'mspectraldynamicsle', 'compression'),
  ('meldaproduction', 'MSpectralPan', 'mspectralpan', 'utilities'),
  ('meldaproduction', 'MStereoGenerator', 'mstereogenerator', 'utilities'),
  ('meldaproduction', 'MStereoProcessor', 'mstereoprocessor', 'utilities'),
  ('meldaproduction', 'MStereoScope', 'mstereoscope', 'utilities'),
  ('meldaproduction', 'MStereoSpread', 'mstereospread', 'utilities'),
  ('meldaproduction', 'MSuperLooper', 'msuperlooper', 'utilities'),
  ('meldaproduction', 'MTotalFXBundle', 'mtotalfxbundle', 'bundles'),
  ('meldaproduction', 'MTrackAlign', 'mtrackalign', 'utilities'),
  ('meldaproduction', 'MTransformer', 'mtransformer', 'utilities'),
  ('meldaproduction', 'MTransient', 'mtransient', 'utilities'),
  ('meldaproduction', 'MTransientMB', 'mtransientmb', 'utilities'),
  ('meldaproduction', 'MTremolo', 'mtremolo', 'utilities'),
  ('meldaproduction', 'MTremoloMB', 'mtremolomb', 'utilities'),
  ('meldaproduction', 'MTuner', 'mtuner', 'utilities'),
  ('meldaproduction', 'MTurboAmp', 'mturboamp', 'guitar-amps'),
  ('meldaproduction', 'MTurboComp', 'mturbocomp', 'utilities'),
  ('meldaproduction', 'MTurboCompLE', 'mturbocomple', 'utilities'),
  ('meldaproduction', 'MTurboDelay', 'mturbodelay', 'reverb-delay'),
  ('meldaproduction', 'MTurboEQ', 'mturboeq', 'eq'),
  ('meldaproduction', 'MTurboFilter', 'mturbofilter', 'utilities'),
  ('meldaproduction', 'MTurboReverbLE', 'mturboreverble', 'reverb-delay'),
  ('meldaproduction', 'MUltraMaximizer', 'multramaximizer', 'mastering'),
  ('meldaproduction', 'MUnison', 'munison', 'utilities'),
  ('meldaproduction', 'MUtility', 'mutility', 'utilities'),
  ('meldaproduction', 'MVibrato', 'mvibrato', 'utilities'),
  ('meldaproduction', 'MVibratoMB', 'mvibratomb', 'utilities'),
  ('meldaproduction', 'MVintageRotary', 'mvintagerotary', 'utilities'),
  ('meldaproduction', 'MVocoder', 'mvocoder', 'utilities'),
  ('meldaproduction', 'MWaveFolder', 'mwavefolder', 'utilities'),
  ('meldaproduction', 'MWaveFolderMB', 'mwavefoldermb', 'utilities'),
  ('meldaproduction', 'MWaveShaper', 'mwaveshaper', 'utilities'),
  ('meldaproduction', 'MWaveShaperMB', 'mwaveshapermb', 'utilities'),
  ('meldaproduction', 'MWobbler', 'mwobbler', 'utilities'),
  ('meldaproduction', 'MXXXCore', 'mxxxcore', 'utilities'),
  ('meldaproduction', 'MeldwayGrand', 'meldwaygrand', 'utilities'),
  ('meldaproduction', 'MonasteryGrand', 'monasterygrand', 'utilities')
) as p(dev_slug, name, slug, category)
join public.developers d on d.slug = p.dev_slug
on conflict (developer_id, slug) do nothing;
