-- Step 32: gap-fill (Victor, 2026-09-24). 5 missing developers plus Sibelius under Avid.
-- Solid State Logic, Scaler Music, MusicLab, Mixed In Key, Boris FX (Sound Forge and Acid Pro,
-- bought from MAGIX in April 2026). Product names from each developer official site/sitemap.
-- Transfer rules from official pages only, unverified policies left as transferable = null.
-- Free products left out (SSL X-Orcism II, LMC+).
-- Run once in Supabase > SQL Editor.

insert into public.developers
  (name, slug, website, transferable, fee, who_pays, process, typical_delay, restrictions, source_url, last_verified, no_fee)
values
('Solid State Logic', 'solid-state-logic', 'https://solidstatelogic.com', true,
 'iLok transfer fee (set by iLok)', null,
 'SSL does not handle transfers itself: the seller moves the SSL plugin licenses from their iLok account to the buyer''s iLok User ID with iLok License Manager and pays iLok''s transfer fee.',
 null,
 'The Production Pack bundled with SSL hardware can''t be transferred. SSL can''t revoke an iLok license that is already activated. SSL Complete (subscription) is not a license you can sell.',
 'https://support.solidstatelogic.com/hc/en-gb/articles/5340267452189-Secondhand-units-and-bundled-software', '2026-09-24', false),
('Scaler Music', 'scaler-music', 'https://scalermusic.com', true,
 null, null,
 'Licenses bought from Plugin Boutique: the seller asks Plugin Boutique support to move the order to the buyer''s account. Licenses bought on scalermusic.com: no transfer process is published yet, ask Scaler Music support first.',
 null,
 'A Plugin Boutique license can be transferred only once and becomes NFR for the buyer, who can''t resell it. If the order holds several products, the whole order must be transferred. A transferred Scaler license is not eligible for upgrade paths.',
 'https://help.pluginboutique.com/hc/en-us/articles/6233304815636-I-want-to-transfer-my-licence-to-someone-else', '2026-09-24', false),
('MusicLab', 'musiclab', 'https://www.musiclab.com', null,
 null, null, null, null,
 'MusicLab doesn''t publish its license agreement or a transfer policy on its own site. Ask MusicLab support (musiclab.com/support/contact-us.html) before buying or selling.',
 null, null, false),
('Mixed In Key', 'mixed-in-key', 'https://mixedinkey.com', false,
 null, null, null, null,
 'Mixed In Key''s terms make its licenses non-transferable: you may not assign, sublicense or otherwise transfer them to anyone else.',
 'https://mixedinkey.com/captain-plugins-eula/', '2026-09-24', false),
('Boris FX', 'boris-fx', 'https://borisfx.com', null,
 null, null, null, null,
 'Boris FX''s license agreement says licenses can''t be transferred without Boris FX''s prior written consent, and there is no published transfer program. Get written approval from Boris FX support before buying or selling a used license. Subscriptions can''t be sold.',
 'https://borisfx.com/store/eula/', null, false);

insert into public.plugins (developer_id, name, slug, category)
select d.id, p.name, p.slug, p.category
from (values
  ('solid-state-logic', 'SSL Native Channel Strip 2', 'ssl-native-channel-strip-2', 'channel-strips'),
  ('solid-state-logic', 'SSL Native Bus Compressor 2', 'ssl-native-bus-compressor-2', 'compression'),
  ('solid-state-logic', 'SSL 4K B Channel Strip', 'ssl-4k-b', 'channel-strips'),
  ('solid-state-logic', 'SSL 4K E Channel Strip', 'ssl-4k-e', 'channel-strips'),
  ('solid-state-logic', 'G3 MultiBusComp', 'g3-multibuscomp', 'compression'),
  ('solid-state-logic', 'SSL Native X-EQ 2', 'ssl-native-x-eq-2', 'eq'),
  ('solid-state-logic', 'X-DynEQ', 'x-dyneq', 'eq'),
  ('solid-state-logic', 'SSL Native X-Saturator', 'ssl-native-x-saturator', 'saturation'),
  ('solid-state-logic', 'SSL Native X-Comp', 'ssl-native-x-comp', 'compression'),
  ('solid-state-logic', 'SSL Native X-ValveComp', 'ssl-native-x-valvecomp', 'compression'),
  ('solid-state-logic', 'SSL Native X-Phase', 'ssl-native-x-phase', 'utilities'),
  ('solid-state-logic', 'SSL Native X-Echo', 'ssl-native-x-echo', 'reverb-delay'),
  ('solid-state-logic', 'SSL X-Delay', 'ssl-x-delay', 'reverb-delay'),
  ('solid-state-logic', 'SSL X-Gate', 'ssl-x-gate', 'utilities'),
  ('solid-state-logic', 'SSL X-Limit', 'ssl-x-limit', 'mastering'),
  ('solid-state-logic', 'SSL Native Drumstrip', 'ssl-native-drumstrip', 'channel-strips'),
  ('solid-state-logic', 'SSL Guitarstrip', 'ssl-guitarstrip', 'channel-strips'),
  ('solid-state-logic', 'SSL Native Vocalstrip 2', 'ssl-native-vocalstrip-2', 'channel-strips'),
  ('solid-state-logic', 'SSL DeEss', 'ssl-deess', 'compression'),
  ('solid-state-logic', 'SSL Native FlexVerb', 'ssl-native-flexverb', 'reverb-delay'),
  ('solid-state-logic', 'PlateVerb', 'plateverb', 'reverb-delay'),
  ('solid-state-logic', 'SpringVerb', 'springverb', 'reverb-delay'),
  ('solid-state-logic', 'GateVerb', 'gateverb', 'reverb-delay'),
  ('solid-state-logic', 'Blitzer', 'blitzer', 'compression'),
  ('solid-state-logic', 'SubGen', 'subgen', 'utilities'),
  ('solid-state-logic', 'Sourcerer', 'sourcerer', 'utilities'),
  ('solid-state-logic', 'Module8', 'module8', 'utilities'),
  ('solid-state-logic', 'Meter', 'meter', 'utilities'),
  ('solid-state-logic', 'Meter Pro', 'meter-pro', 'utilities'),
  ('solid-state-logic', 'SSL Fusion Vintage Drive', 'ssl-fusion-vintage-drive', 'saturation'),
  ('solid-state-logic', 'SSL Fusion Violet EQ', 'ssl-fusion-violet-eq', 'eq'),
  ('solid-state-logic', 'SSL Fusion HF Compressor', 'ssl-fusion-hf-compressor', 'compression'),
  ('solid-state-logic', 'SSL Fusion Stereo Image', 'ssl-fusion-stereo-image', 'utilities'),
  ('solid-state-logic', 'SSL Fusion Transformer', 'ssl-fusion-transformer', 'saturation'),
  ('solid-state-logic', 'autoBUS', 'autobus', 'compression'),
  ('solid-state-logic', 'autoDYN', 'autodyn', 'compression'),
  ('solid-state-logic', 'autoEQ', 'autoeq', 'eq'),
  ('scaler-music', 'Scaler 3', 'scaler-3', 'utilities'),
  ('scaler-music', 'Scaler EQ Pro', 'scaler-eq-pro', 'eq'),
  ('scaler-music', 'Carbon Electra 2', 'carbon-electra-2', 'synths'),
  ('scaler-music', 'DC Snares', 'dc-snares', 'sample-libraries'),
  ('scaler-music', 'Scaler Detector', 'scaler-detector', 'utilities'),
  ('musiclab', 'RealGuitar 6', 'realguitar-6', 'sample-libraries'),
  ('musiclab', 'RealStrat 6', 'realstrat-6', 'sample-libraries'),
  ('musiclab', 'RealLPC 6', 'reallpc-6', 'sample-libraries'),
  ('musiclab', 'RealRick 6', 'realrick-6', 'sample-libraries'),
  ('musiclab', 'RealEight 6', 'realeight-6', 'sample-libraries'),
  ('musiclab', 'RealGMS', 'realgms', 'sample-libraries'),
  ('musiclab', 'RealTele', 'realtele', 'sample-libraries'),
  ('mixed-in-key', 'Mixed In Key 11', 'mixed-in-key-11', 'utilities'),
  ('mixed-in-key', 'Mixed In Key 11 Pro', 'mixed-in-key-11-pro', 'utilities'),
  ('mixed-in-key', 'Mixed In Key Studio Edition', 'mixed-in-key-studio-edition', 'utilities'),
  ('mixed-in-key', 'Mixed In Key Live', 'mixed-in-key-live', 'utilities'),
  ('mixed-in-key', 'Captain Plugins', 'captain-plugins', 'utilities'),
  ('mixed-in-key', 'Platinum Notes', 'platinum-notes', 'mastering'),
  ('mixed-in-key', 'Human Plugins', 'human-plugins', 'utilities'),
  ('boris-fx', 'Sound Forge 2026', 'sound-forge-2026', 'daw'),
  ('boris-fx', 'Acid Pro 2026', 'acid-pro-2026', 'daw'),
  ('avid', 'Sibelius Ultimate (Perpetual)', 'sibelius-ultimate-perpetual', 'daw'),
  ('avid', 'Sibelius Artist (Perpetual)', 'sibelius-artist-perpetual', 'daw')
) as p(dev_slug, name, slug, category)
join public.developers d on d.slug = p.dev_slug
on conflict (developer_id, slug) do nothing;
